### ISSUE TITLE
Preparar el repositorio "asociacion"

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#1]
Tal y como se presento en la candidatura de junta, nos hemos propuesto utilizar issues de github para documentar todo el labor de la junta. Esta es la primera de muchas issues.

- [x] Documentar el objetivo del repositorio en el README
- [x] Crear labels para categorizar el trabajo
- [x] Transformar el plan de la junta en issues
- [x] Documentar como participar y su uso como metodo de contacto

**Comment by Juanlu001** [comment]
Y cuando esto esté listo,

* [ ] Anunciarlo como un método más para ponerse en contacto con la Junta y la Asociación

**Comment by mariocj89** [comment]
Todo listo, hechad un ojo [a las issues](https://github.com/python-spain/asociacion/issues).

solo una pregunta, queremos dos issues "in progress" y "to do" o simplemente una "in progress" y todo lo que no esta in progress y esta abierto es claramente "to do".
O incluso mas sencillo, necesitamos un "in progress"? No nos vale con tener una persona asignada?

**Comment by Juanlu001** [comment]
Para mí "to do" significa "hemos visto este issue, y lo hemos añadido al backlog". La ausencia de etiqueta sería entonces "aún no hemos visto este issue o no hemos decidido qué hacer con él: podríamos cerrarlo, o añadirlo al to do". Pero tampoco tengo una opinión fuerte al respecto.

Sobre lo de "in progress" y tener una persona asignada, lo veo parecido: una issue puede tener una persona asignada, pero esa persona puede no haber empezado a trabajar.

**Comment by Juanlu001** [comment]
Anuncio hecho en Twitter https://twitter.com/python_es/status/981439039243988992 y en la lista de correo de socios. ¡Podemos ir cerrando esto!
