### ISSUE TITLE
Creación grupo announces@

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#101]
Para difundir / reenviar eventos y comunicaciones de interés para organizadores de comunidades locales

Relacionado con https://comunidad.es.python.org/t/canales-de-comunicacion-para-las-comunidades/276/18

**Comment by XaviTorello** [comment]
Grupo creado y primera tanda de comunidades añadidas.

Dejamos issue abierta por si hiciera falta algún cambio durante los próximos días.

**Comment by dukebody** [comment]
Creo que esto ya está y funciona, cierro tarea.
