### ISSUE TITLE
Definir/implementar sistema para compartir credenciales de forma segura

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#104]
Viene siendo necesario disponer de un sistema que nos permita definir y compartir de forma segura credenciales.

Algunos requisitos (añadid/modificad lo que consideréis):
1) Que permita definir grupos para compartir de forma simplificada
2) Que sea una solución altamente utilitzada / validada por la comunidad
3) A poder ser que no esté on-premises / self-hosted para evitar tener que estar encima validando el nivel de seguridad del entorno constantemente
4) OS a poder ser! :beers:
5) No me importaría pagar por el servicio

**Comment by bameda** [comment]
Como propuesta está Bitwarden (SaSS), aunque el número de usuarios puede que dispare el precio. Otras alternativas interesantes es KeepassXC, aunque habría que buscar SaSS para que no dependa de nosotros. [Más info](https://blog.kaleidos.net/Como-escapar-del-infierno-de-las-contrasenas/)

**Comment by XaviTorello** [comment]
Cierto, se dispara bastante de precio... Si contamos JD y GT saldría por un buen pico, además la necesidad es solo la de poder compartir las claves de forma segura entre grupos. Quiero decir que ni SSO, ni rotado automático, ni ninguna de las otras funcionalidades que proporcionan nos interesarían a priori, no? //por si realmente hay algo que justifique el coste relacionado

Como alternativa podríamos desplegar la solución elegida on-premises en una "zona segura" con acceso via VPN. Nos ahorramos la cifra disparatada mensual y conseguiríamos cubrir la necesidad básica sin correr tantos riesgos exponiendo el servicio en todo inet. Además podría ser un servicio más que podríamos aportar a las comunidades locales 👀 

La otra opción que se me ocurre es contactar con ellos explicando que somos una Asociación sin ánimo de lucro, a ver si nos pueden ofrecer algún plan un poco más asequible.

A malas siempre tenemos la opción de crear un XLS en la unidad compartida del GT con las credenciales relacionadas xDD

**Comment by yamila-moreno** [comment]
Bitwarden cuesta 40$ al año, y puedes tener 6 cuentas. Este precio me parece totalmente aceptable.

![imagen](https://user-images.githubusercontent.com/3340793/96334845-09b46480-1074-11eb-8b81-de70b6a69566.png)

**Comment by JohnnyVM** [comment]
A mí, por lo que leo me parece que lo que estáis buscando es un servidor LDAP preparado para compartir credenciales.
También es cierto que LDAP puede ser excesivamente complejo, desconozco si hay alternativas más sencillas.

**Comment by dukebody** [comment]
¿Qué os parece un archivo KeePass compartido mediante Google Drive, GitHub o Dropbox? No cambiaremos claves muy a menudo, por lo que no debería haber problemas de sincronización.

**Comment by XaviTorello** [comment]
Up de este thread

Alguna otra opción?

De todo lo que se ha comentado en esta issue, la opción que veo más interesante es la de [Bitwarden](https://github.com/python-spain/asociacion/issues/104#issuecomment-710801152). Una cuenta para JD y 5 más para los GTs que lo requieran (p.e Comunicación, Infra, PyConES, ...)

Al final "sólo" necesitamos algo que nos permita compartir de forma segura y sin demasiados quebraderos de cabeza credenciales de acceso entre GTs, no?

Thoughts?

**Comment by yamila-moreno** [comment]
+1 a bitwarden

**Comment by humitos** [comment]
Solo vengo a decir que me pasé de LastPass a Bitwarden hace 2 años y estoy muy contento con su servicio tanto en desktop (Firefox + AddOn) como en móvil.

**Comment by XaviTorello** [comment]
En esta última reunión de JD feb'22 hemos acordado crear una cuenta gratuita en Bitwarden para volcar todas las credenciales de la Asociación.

La idea es no condicionar a la siguiente JD, entregaremos la cuenta gratuita a la siguiente JD para que puedan estudiar opciones para gestionarlo.

**Comment by dukebody** [comment]
¡Ya tenemos el Bitwarden!
