### ISSUE TITLE
Definir criterios de publicación para canal de Telegram

### ISSUE THREAD

**Issue by bameda** [python-spain/asociacion#114]

**Comment by dukebody** [comment]
@bameda ¿criterios de publicación de ofertas de trabajo? ¿O de qué?

**Comment by bameda** [comment]
Sobre qué contenido se publica. El criterio al que se llegó en una reunión del GT de Comm para la publicación de contenido es similar al de Twitter. Puesto que el número de personas con permisos para publicar es reducido actualmente (2 o 3), creo que no hace falta dejarlo por escrito de un modo más formal.
