### ISSUE TITLE
Crear agenda de contactos GTs y Comunidades

### ISSUE THREAD

**Issue by bameda** [python-spain/asociacion#116]
Crear un documento con el listado de contactos de los GTs de la asociación, las comunidades locales y otras que puedan ser de interés.

**Comment by bameda** [comment]
Existe una primera versión en una Hoja de Cálculo en el disco virtual de GT Comm con el nombre "Contactos"

**Comment by bameda** [comment]
TODO: Tengo que actualizarlo a partir del contenido que aporte Xavi

**Comment by dukebody** [comment]
Lo tenemos en un documento de acceso por la gente de todas las comunidades que se llama "Inventario de comunidades".
