### ISSUE TITLE
Proponer procedimiento alta socio en GSuite

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#117]
Preparar un draft del proceso / procedimiento y validarlo con GT Infra

Ideas generales:
1. Socio manda solicitud a it@
2. GT Infra se encarga de prepararlo y notifica al socio

Una vez lo tengamos claro, abrir thread en Discourse (+visibilidad por mail / grupo Telegram de Socios) para explicar el proceso y que cualquier socio pueda empezar a solicitarlo.

**Comment by XaviTorello** [comment]
Indicar en correo de alta si se quiere mail (campo en formulario de app web futuro).

Quien quiera de socios actuales que lo pida por formulario GDocs.

### Todo

- Crear form en unidad compartida JD para solicitar cuenta GSuite
- Comunicar en socies / Discourse
- Modificar texto informativo alta socio
  - https://github.com/python-spain/web/blob/master/content/pages/hazte-socio.md

**Comment by XaviTorello** [comment]
Draft del form creado https://docs.google.com/forms/d/e/1FAIpQLScsqOP8u9ndDc14FXT5kCe2AyQriGQCPrSM0l_FCveLUvjYkw/viewform

**Comment by dukebody** [comment]
@XaviTorello @yamila-moreno ¿y si creásemos todas las cuentas de golpe para todos y todas los y las socias actuales activas, poniendo como email de recuperación el que tienen registrado con Python España? Sin necesidad de rellenar ningún formulario. Y si luego no las usan, pues nada, ya que salen gratis.

Así ahorramos pasos.

**Comment by XaviTorello** [comment]
No lo veo del todo mal, lo que quizá alguien se molesta por crear la cuenta GSuite sin haberlo solicitado 🤷🏻

Avanzo con el texto explicativo y si hace falta añadir algo relativo a la alta masiva de socios lo añadimos

**Comment by XaviTorello** [comment]
```
¡Buenos días socies!

Os escribimos para contaros que hemos preparado un pequeño procedimiento para que podáis solicitar cuentas bajo el dominio de la Asociación.

Podéis solicitar una cuenta de correo @es.python.org con todos los servicios añadidos de Google Workspace (anteriormente GSuite), incluyendo Drive personal con 30GB de storage.

Para ello solo tenéis que realizar la solicitud de cuenta PythonES, y en unos días el GT IT se encargará de prepararlo todo.

Si tenéis cualquier duda o comentario no dudéis en hacérnoslo llegar a junta@es.python.org

Gracias a todes,
```

Lo veis bien así?

**Comment by yamila-moreno** [comment]
> @XaviTorello @yamila-moreno ¿y si creásemos todas las cuentas de golpe para todos y todas los y las socias actuales activas, poniendo como email de recuperación el que tienen registrado con Python España? Sin necesidad de rellenar ningún formulario. Y si luego no las usan, pues nada, ya que salen gratis.
> 
> Así ahorramos pasos.

creo que no deberíamos crear cuentas de correo para gente que no lo haya pedido expresamente

**Comment by yamila-moreno** [comment]
> ```
> ¡Buenos días socies!
> 
> Os escribimos para contaros que hemos preparado un pequeño procedimiento para que podáis solicitar cuentas bajo el dominio de la Asociación.
> 
> Podéis solicitar una cuenta de correo @es.python.org con todos los servicios añadidos de Google Workspace (anteriormente GSuite), incluyendo Drive personal con 30GB de storage.
> 
> Para ello solo tenéis que realizar la solicitud de cuenta PythonES, y en unos días el GT IT se encargará de prepararlo todo.
> 
> Si tenéis cualquier duda o comentario no dudéis en hacérnoslo llegar a junta@es.python.org
> 
> Gracias a todes,
> ```
> 
> Lo veis bien así?

propuesta: storage > almacenamiento
aparte, si esto es un correo no entiendo bien el procedimiento cuando dice "solo tenéis que realizar la solicitud de cuenta PythonES", ¿dónde se realiza? creo que falta indicar cuál es el paso. ¿un correo a it@es.python.org?

**Comment by dukebody** [comment]
¡Hola! Unas cositas nada más:
- Intentaría plantearlo un poco más como regalo molón que estamos dando a socios/as.
- Enlace al formulario para pedir la cuenta.
- Mejor que escriban a it@es.python.org si tienen dudas, ¿no?

Propuesta:

--- 
¡Buenos días socies!

Esta primavera os traemos un regalo superchulo: ¡una cuenta vuestronombre@es.python.org! 

Con ella tendréis acceso a todos los servicios de Google Workspace (anteriormente GSuite), incluyendo cuenta de Gmail y Drive personal con 30GB de almacenamiento.

Para solicitarla, por favor rellenad el siguiente formulario: https://docs.google.com/forms/d/19esbLPWJXTgQZKRy_tfp33UuM6typivFEqBFleqHUjk/viewfor

¿Dudas? Escribid a it@es.python.org.

¡A disfrutar!

**Comment by XaviTorello** [comment]
@yamila-moreno el link estaba en "la solicitud de cuenta PythonES" al pastear rápido perdí links :(

Veo mejor el texto de @dukebody, pa'lante!

Thread abierto en https://comunidad.es.python.org/t/cuentas-gsuite-es-python-org-para-socies/538, y mensaje mandado al [grupo de socies en Telegram](https://t.me/c/1218250234/1989)

**Comment by XaviTorello** [comment]
@dukebody copié literalmente tu texto sin revisar el form 😨  que apunta a otro form, lo modifico en zerocoma
