### ISSUE TITLE
Newsletter interna

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/asociacion#118]
## Newsletter interna

- Lista de emails de grupos de trabajo + comunidades
- Compilar contenido en texto plano ~una vez cada dos meses
- Maquetar con MailJet

### Ideas de contenido
- meetups de los últimos dos meses
- noticias interesantes (alguien de la comunidad fue Keynoter)
- ofertas de empleo
- grupos de trabajo

**Comment by dukebody** [comment]
Sobre newsletters internas y qué puede ser interesante.

En PyData Salamanca que está muy guay es hacer en Twitter un hilo semanal resumen de cosas importantes:
https://twitter.com/PydatalabUSAL/status/1351802216739434497

Ejemplo de una newsletter que me parece eficiente en el formato:
https://devrelweekly.com/issues/126#start

¿Por qué? Porque tiene:
- Introducción _personal_ con información importante y cercana. Ayuda a crear conexión con la audiencia.
- Lista muy corta de bits de contenido importante - en este caso Tweets. Puede parecer un poco absurdo poner tweets en una newsletter, pero dada la vorágine de Twitter, es muy fácil que te pierdas cosas y esto es una selección.
- Enlaces a artículos más largos _y entradilla explicando por qué son interesantes_. La entradilla me parece lo más importante.
- Enlaces a charlas y episodios de podcasts interesantes nuevos.
- Próximos eventos
- Ofertas de trabajo

¡Espero que os dé ideas!

**Comment by dukebody** [comment]
De cara a la elaboración de la newsletter, sería guay tener para cada una de ellas un documento colaborativo donde las personas editoras vayan volcando a saco todo lo que les haya parecido interesante durante ese tiempo. Así cuando haya que preparar el envío solamente habría que seleccionar el contenido entre todo lo que se ha ido apuntando.

**Comment by dukebody** [comment]
Objetivo: sacar al menos una edición de la newsletter este trimestre.

**Comment by astrojuanlu** [comment]
> al menos una edición

¡Conseguido!
