### ISSUE TITLE
Mover hosting de es.python.org a GH pages

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#119]
Estamos sirviendo todas las webs de PyConES desde GH pages.

La web principal de la asociación, https://es.python.org, es estática y se sirve desde un servidor propio, pero lo podemos mover a GH pages y dejar de pagar el servidor.

**Comment by yamila-moreno** [comment]
Podemos mover la web de la asociación, no sería mala idea de hecho, pero no podemos apagar el servidor porque tiene más servicios.
