### ISSUE TITLE
PyCena

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#12]
Organización de un evento de encuentro para socios en el que conocerse y discutir el estado y futuro de la asociación.

**Comment by mariocj89** [comment]
¡Lanzado! https://comunidad.es.python.org/t/la-pycena-2019-ya-esta-aqui/78

**Comment by Vital-Fernandez** [comment]
Recibí la notificación de la pycena por email con este link pero pero no tengo "acceso a este tema" en la pagina de discourse... ¿Hay que pedir algún tipo de permiso? (ya abrí cuenta en la pagina).

**Comment by Juanlu001** [comment]
Buenas @Vital-Fernandez! Mandé invitación al Discourse a los socios que estaban al corriente de pago pero es posible que me equivocase. Por otro lado, @marcosgabarda estaba un poco hasta arriba pero pronto iba a empezar a mandar recordatorios y domiciliaciones. Ya que lo has comentado y para evitar bloqueos absurdos, te he dado los privilegios necesarios. Mientras tanto, por favor comprueba tu última cuota :)

**Comment by Vital-Fernandez** [comment]
Muchas gracias @Juanlu001 . Ahora iba a mandar un email para preguntar si se podía renovar la cuota durante la cena: No tengo ninguna cuenta bancaria aquí pero ya encontraré alguna manera.
