### ISSUE TITLE
Preparar estructura dinamización Asamblea General Ordinaria 2021

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#127]
Queremos hacer la Asamblea General Ordinaria de 2021 más participativa para recabar la opinión y sugerencias de socios y socias. Preparar estructura para dinamizarla.

**Comment by dukebody** [comment]
Para poder incorporar las ideas de todo el mundo más fácilmente, había pensado lo siguiente:

1. Avances desde la última asamblea general.
2. Cualquier cosa que se tenga que votar/aprobar en concreto (p. ej. cambio de estatutos).
3. Sesión retrospectiva/futurospectiva. Podemos utilizar un tablero parecido a éste: https://metroretro.io/templates/the-hot-air-balloon-retrospective
4. Ruegos y preguntas, que no encajen en lo anterior.

Lo importante para la dinamización es el punto 3. Una idea:
- Dividimos a la gente en grupos de 3/4 personas (breakout rooms) que con ayuda de su propio tablero discutan qué ha ido bien y mal este año, y qué oportunidades y problemas nos esperan. Votan para conseguir un máximo de 3 temas principales por cada cuadrante.
- Nos juntamos tod@s de nuevo y una persona de cada grupo expone en un tablero común los tres temas más votados por cuadrante. Agrupamos los temas que coincidan y discutimos posibles acciones/soluciones a los temas más populares.

Como véis, hay una parte en grupos pequeños y otra en global. Al hacer inicialmente grupos pequeños es más fácil que la gente manifieste su opinión, incluso gente que en un espacio muy grande no se atrevería y crea un poco de calor humano. Además, produce un primer filtrado de ideas que focalizará luego la discusión en lo que más gente considera importante.

**Comment by dukebody** [comment]
He creado el siguiente tablero de ejemplo:
![image](https://user-images.githubusercontent.com/41953/107872119-1cb33600-6ea8-11eb-8935-65b4c3e055ba.png)

Ideas nuevas a continuación.

En base a lo que hablamos en la última Junta, simplificar el tablero y poner dos cuadrantes con "cosas buenas" y "cosas malas" en vez de cuatro. Lo he basado en el de "Hopes & Concerns" y lo he rebautizado como "Me gustaría / No me gustaría", incidiendo un poco en los subtítulos en "oportunidades" y "posibles problemas".

Para limitar un poco el tiempo y evitar que la asamblea se haga demasiado larga, he pensado en limitar la discusión a solamente entre los grupos pequeños. Es decir, se proponen y discuten ideas en los grupos pequeños, y una persona de cada grupo lleva el resumen de lo hablado a la sala general de la asamblea, pero ahí ya no se discute, sino que lo dejamos divergente. Mi idea es que hagamos reuniones monográficas para discutir los temas más importantes que salgan en un futuro, donde asista la gente que le interese. Creo que así será más fácil llegar realmente a acciones concretas que intentar finiquitar cada tema en 10 minutos en la asamblea general.

Tal y como hablamos en la Junta, sería ideal que en cada sub-grupo hubiese una persona de la Junta que actúe de dinamizadora y ayude en lo que sea necesario. Esto nos permitiría hacer un máximo de 7 grupos, que yo creo que son suficientes.

**Comment by yamila-moreno** [comment]
buenas!

Sobre la **dinámica**
Dividir a los asistentes en grupos me parece una idea estupenda. Creo que dará lugar a conversaciones interesantes. A la parte de la convergencia le pediría muy poco puesto que es un ejercicio complicado.

Sobre el **panel**
El *wording* es complementario tal y como lo veo. Me gustarían cosas y no me gustaría la ausencia de esas cosas.
Mi propuesta soft es:
- Me gustaría empezar (qué me gustaría que la Asociación hiciera, o qué me gustaría que hiciera la Junta Directiva)
- Me gustaría mejorar (qué sucede actualmente en la Asociación que habría que mejorar o que puedan causar preocupación)
- [Bonus] Me ha gustado mucho (para saber qué acciones han sido bien recibidas)

**Comment by dukebody** [comment]
¡Me gusta tu idea de panel @yamila-moreno ! Es cierto que la contraposición me gusta / no me gusta es complementaria y por ende algo repetitiva, ya lo vimos en la reunión de brainstorming de la PyConES 2021.

Si el resto de la @python-spain/junta-directiva está de acuerdo, ponemos ese panel que tú dices y palante. :)

**Comment by yamila-moreno** [comment]
Para el panel podemos usar la funcionalidad de "hide postits" si queremos que los grupos no se "espíen" y generen cuanta divergencia se pueda mejor

**Comment by dukebody** [comment]
listo, ueeee!
