### ISSUE TITLE
No funciona el envío de emails del foro de Discourse

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#128]
Creo que puede haber algún problema con la configuración de correo de Discourse.
- Se ha dado de alta un nuevo socio pero no le ha llegado el mail de activación y he tenido que activarle a mano.
- Si voy al panel de configuración y trato de enviar un mail de prueba me da un error.

Veo que el último mail enviado es del 14 de enero, así que definitivamente parece que hay algo roto.

**Comment by dukebody** [comment]
¿Podría ser https://www.scaleway.com/en/faq/why-can-i-not-send-any-email/  ?  En los logs aparece lo siguiente:
![image](https://user-images.githubusercontent.com/41953/111370707-d7e21100-8698-11eb-9e10-d8bba40aa6f4.png)
https://meta.discourse.org/t/issue-with-smtp-server-setup/139035

**Comment by dukebody** [comment]
¡Arreglado! Era https://meta.discourse.org/t/discourse-smtp-sends-ehlo-localhost-instead-of-domain-breaking-google-smtp-relay/176755/19.

A partir de ahora Google no acepta dominios genéricos en el saludo.

Lo hemos arreglado añadiendo la variable en `containers/new.yml`:
```
 DISCOURSE_SMTP_DOMAIN: comunidad.es.python.org
```

Importante: NO poner nombre de usuario y contraseña, ya que tenemos puesto que use el relay sin autenticar. Si se intenta autenticando falla siempre, no sabemos por qué :(

**Comment by dukebody** [comment]
Nota: sí se puede poner `DISCOURSE_SMTP_ENABLE_START_TLS: true` y funciona, con lo que el contenido está cifrado.

**Comment by dukebody** [comment]
Hemos vuelto a tener este problema de nuevo. Al actualizar Discourse a la última versión el 28 de octubre utilizamos la plantilla `app.yml` en lugar de `new.yml`, lo que creó un contenedor con la configuración que tenía este problema.

Lo que he hecho:
- Renombrado `app.yml` a `old-do-not-use.yml` en la carpeta `containers`.
- Renombrado `new.yml` a `app.yml` de la misma carpeta.
- Ejecutar `./launcher rebuild app`, cruzar los dedos y... voilà!

**Comment by XaviTorello** [comment]
Genial, gracias @dukebody!
