### ISSUE TITLE
Canal de empleo

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#13]
Creación de un canal de empleo en el que poder distribuir ofertas de empleo para los socios de la asociación que estén interesados.

**Comment by Juanlu001** [comment]
Hubo un intento aquí https://github.com/python-spain/python-jobs pero se quedó parado, @gnufede sabe más :)

**Comment by mariocj89** [comment]
Creada una categoría que se va a usar con ese proposito en discourse: https://comunidad.es.python.org/c/empleo
