### ISSUE TITLE
Documentación de inventario y procedimientos de infraestructura

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#130]
- DNS
- Mailing
- Servidores Scaleway
- ...

**Comment by XaviTorello** [comment]
@yamila-moreno buscamos 5' esta semana y acotamos el alcance? Cerrar el listado de temas a documentar creo que ayudaría a darle un empujón al tema, como lo ves?

**Comment by aalmiramolla** [comment]
Hola @dukebody,
Hemos estado hablando @alexgmin y yo, y hemos acordado el siguiente plan de acción para este issue:

- Obtener acceso al Bitwarden(?) para tener los credenciales de los servicios
- Investigar el Scaleway para ver qué máquinas virtuales tienen y que tiene cada una.
- Investigar otros servicios como DNS, Mailing, etc. (comprobar con Bitwarden)
- Crear un documento (Excel, doc., etc.) con todos los servicios, si tienen las credenciales guardadas en el Bitwarden, etc.

Si te parece bien, danos acceso a lo que corresponda y nos ponemos manos a la obra.

**Comment by dukebody** [comment]
Hola!

Genial el plan. Gracias por tirar esto adelante.

- os añado al grupo de it de telegram para que os pasen la master password
del bitwarden.
- en el Drive donde os añadí ya hay un par de documentos con los servicios
que hay. Están desactualizados, pero los podéis tomar como base, unificar y
actualizar.

**Comment by aalmiramolla** [comment]
WIP Reporte de tarea:
- Hemos creado en el grupo de drive GT IT un documento, `Inventario 2023`
- Tenemos varias preguntas:
    - MailJet: ¿Cuenta? ¿Quién lo gestiona?
    - ¿Todos los subdominios que gestiona jcea.es se pueden eliminar? Parece que ya no se usan y apuntan a servicios antiguos.
    - El planet.es.python.org apunta a oscarmlage.com. ¿Se sigue utilizando el planet? ¿Se puede borrar? ¿Quién lo aloja?
    - El moodle de PyLadies tiene el certificado expirado desde hace un año, ¿se sigue utilizando este servicio?
    - ¿Dónde está alojado hacktoberfestes.dev? Parece Google Cloud con Netlify??.
    - El dominio hacktoberfestes.dev expira en 2 semanas, ¿qué hacemos al respecto?

¿Qué nos falta para hacer el próximo día?
- [ ] Meternos en las instancias de Scaleway para ver como están gestionados los servicios

**Comment by dukebody** [comment]
Hola @aalmiramolla . Gracias por el curro.


- MailJet: ¿Cuenta? ¿Quién lo gestiona?
Tenemos una cuenta con las credenciales en otro lugar. Lo gestionamos desde la Junta, pero tienen acceso más personas colaboradoras, especialmente para la PyConES.

- ¿Todos los subdominios que gestiona jcea.es se pueden eliminar? Parece que ya no se usan y apuntan a servicios antiguos.
Sí.

- El planet.es.python.org apunta a oscarmlage.com. ¿Se sigue utilizando el planet? ¿Se puede borrar? ¿Quién lo aloja?
Mejor borrarlo, porque no se mantiene activamente ni tengo claro quién lo aloja. Habría que quitar también el enlace desde el pie de la web es.python.org.


- El moodle de PyLadies tiene el certificado expirado desde hace un año, ¿se sigue utilizando este servicio?
Te lo puede contestar @yamila-moreno .

- ¿Dónde está alojado hacktoberfestes.dev? Parece Google Cloud con Netlify??.
Está en Github pages: https://github.com/HacktoberfestES/hacktoberfestES2022-web. Yo soy owner de la organización, y @cmaureir también ha colaborado mucho en el pasado.

- El dominio hacktoberfestes.dev expira en 2 semanas, ¿qué hacemos al respecto?
Todo depende de si sacamos adelante https://github.com/python-spain/asociacion/issues/68. Lo estoy intentando mover con @cprada87 . Por lo que cuesta, yo creo que merece la pena renovarlo e intentar montar algo. Si este año al final no sale nada, al siguiente no lo renovamos y punto.

**Comment by alexgmin** [comment]
> * ¿Dónde está alojado hacktoberfestes.dev? Parece Google Cloud con Netlify??.
>       Está en Github pages: https://github.com/HacktoberfestES/hacktoberfestES2022-web. Yo soy owner de la organización, y @cmaureir también ha colaborado mucho en el pasado.

Ahora no recuerdo como vimos lo de google cloud (Creo que fallo mio), pero Netlify si que parece estar delante y no parece apuntar a una ip de Github Pages

Haciendo un dig
```
;; ANSWER SECTION:
hacktoberfestes.dev.	111	IN	A	75.2.60.5
```

![image](https://github.com/python-spain/asociacion/assets/8340441/85092fbe-11a7-4c20-9f15-c0de3f131a7d)


```
PING hacktoberfestes.dev (75.2.60.5) 56(84) bytes of data.
64 bytes from acd89244c803f7181.awsglobalaccelerator.com (75.2.60.5): icmp_seq=1 ttl=246 time=13.9 ms
```

Si entras a acd89244c803f7181.awsglobalaccelerator.com devuelve una página de error de Netlify

**Comment by dukebody** [comment]
@alexgmin uy, sí, perdona. Hice el cambio a un sitio de Netlify enlazado a un equipo que se llama Python España. Al menos yo tengo acceso al equipo. No le puedo dar acceso a más gente con el plan que tengo. Si queremos traspasarlo, tendríamos que crear una cuenta con un buzón separado y compartir la contraseña.

**Comment by aalmiramolla** [comment]
Tareas realizadas:

Seguramente deberíamos de haber creado otro issue para esto, pero ya se ha realizado, por lo tanto, lo documento por aquí para tenerlo claro.

- Se ha procedido a eliminar todo lo relacionado con jcea.es.
- Se ha eliminado él planet.es.python.org y se ha creado el PR(https://github.com/python-spain/web-ng/pull/141) eliminándolo del footer.
- Se ha actualizado el certificado del Moodle de PyLadies @yamila-moreno y configurada la renovación automática.

Por otro lado, ya se ha finalizado el excel (Inventario 2023) con todo el inventario.


@dukebody desde el CdMon se gestionan los DNS de la TabularConf. Creo que dicha conferencia ya no se volvió a realizar. ¿Eliminamos la gestión? ¿La dejamos? ¿Cómo procedemos?

Gracias!

**Comment by dukebody** [comment]
Genial! Mil gracias por el currazo!

Sobre Tabularconf, efectivamente la conferencia no se volvió a realizar y
el dominio está transferido a otra persona, con lo que podéis borrar los
registros del DNS de Cdmon. Si eso haced una captura de pantalla o
exportación antes por tener copia de seguridad por lo que sea.

Salud!

**Comment by aalmiramolla** [comment]
Damos por cerrada esta issue, ya que en la carpeta Inventario, fichero Inventario 2023 se encuentra la documentación de las máquinas y servicios.

**Comment by dukebody** [comment]
@aalmiramolla gracias!
