### ISSUE TITLE
Formulario de inscripción de newsletter

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#135]
en la web principal

**Comment by dukebody** [comment]
@marcosgabarda ¿qué opinas sobre usar directamente Mailjet para llevar la lista de miembros/as?

**Comment by dukebody** [comment]
En la Junta decidimos NO usar el newsletter de Mailjet para llevar la lista de miembros, sino hacer esa lista como algo separado.

Queremos seguir poniendo la subscripción a la newsletter en la web principal. Lo haremos como parte de https://github.com/python-spain/asociacion/issues/132, porque no merece la pena ya ponerlo en la web actual.

**Comment by bameda** [comment]
Hecho en https://github.com/python-spain/web/commit/f912f5706e495708c92f41d005f721aa6cfcb3d5
