### ISSUE TITLE
Recetario para eventos y comunidades

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#14]
Crear un recetario para la creación de nuevos eventos y comunidades.

**Comment by Juanlu001** [comment]
@gnuites empezó algo pero faltó impulso por mi parte.

**Comment by maigimenez** [comment]
Se trata el tema por primera vez en el [acta](actas/acta-2018-04-08.rst) del 8 de Abril de 2018.

**Comment by mariocj89** [comment]
Este fin de semana voy a hablar en persona para iniciar/evaluar la idea con Lorena mesa y la PSF

**Comment by mariocj89** [comment]
Hemos estado trabajando en [esta plantilla](https://trello.com/b/65ADMKu6/python-event-template) para eventos. Estamos en contacto con la PSF.

**Comment by mariocj89** [comment]
Publicado en https://comunidad.es.python.org/t/plantilla-para-eventos-de-python/174
