### ISSUE TITLE
Explicar en la web cómo realizar solicitudes a GT IT

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#141]
Explicar en la web cómo realizar solicitudes a GT IT
- Mail a it@es.python.org o bien
- [Crear ticket directamente en GH](https://github.com/python-spain/asociacion/issues) y mencionar a @python-spain/gt-it

**Comment by dukebody** [comment]
Añadido del texto 

> Si necesitas algo de este grupo, envía un email a [it@es.python.org](mailto:it@es.python.org) o crea directamente una [issue en GH](https://github.com/python-spain/asociacion/issues) mencionando al equipo [@python-spain/gt-it](https://github.com/orgs/python-spain/teams/gt-it/).

a https://es.python.org/participa/

Y cambiado el nombre a IT.
