### ISSUE TITLE
Propuesta política de actualizaciones

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#142]
La idea es empezar con un draft de política de actualizaciones de sw:
- Revisión periódica
- Scope
  - OS
  - sw / servicios
- Automatización en medida de lo posible

Relacionado con [el invetario de servicios](https://github.com/python-spain/asociacion/issues/130)

**Comment by dukebody** [comment]
Si movemos todos los servicios a hosting externo ya no tendremos que preocuparnos de actualizar nada, ni sistema operativo ni las apps en sí.

**Comment by sincorchetes** [comment]
Quedaría pendientes las siguientes máquinas de la infra:
* moodle-pyladies
* python-es (a espera de Python Madrid para ser apagada)
* discourse (a espera de que pase la semana para ver que la migración funciona correctamente)
* ye-olde-python-es (está apagada pero no sé si consumirá también por ocupar recursos)

**Comment by sincorchetes** [comment]
Se ha apagado ya python-es y discourse, solo está encendida moodle-pyladies.

**Comment by sincorchetes** [comment]
Se ha apagado el servidor que contenía python-es y python-mad
Se ha apagado el servidor dónde alojábamos el discourse

Falta por definir qué hacer con pyladies.

Solo contiene estos usuarios:
```
MariaDB [moodle]> SELECT username FROM mdl_user;
+---------------+
| username      |
+---------------+
| admin         |
| begonia_XXX |
| guest         |
+---------------+
3 rows in set (0.001 sec)
```
Y solo contiene 3 cursos hechos:

````
+----+-----------------------------+
| id | shortname                   |
+----+-----------------------------+
|  5 |  Te sabes la capital de...? |
|  1 | PLMAprende                  |
|  2 | Python Principiante         |
+----+-----------------------------+
````
Creo que deberíamos utilizar plataformas como Google Classroom cuando se de.

**Comment by sincorchetes** [comment]
Hemos eliminado hoy el último servidor, por lo que conluímos con esta issue.
