### ISSUE TITLE
Estandarizar gestión de docker containers en instancias

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#146]
Ahora mismo tenemos 4 instancias en Scaleway con varios servicios, que se despliegan de formas diferentes cada uno.

Queremos estandarizar en la medida de lo posible la gestión de estos recursos, simplificando lo máximo posible.

Tareas: 
- [x] Realizar reconocimiento de las diferentes instancias para ver qué tienen y cómo está configurado.
- [ ] Crear propuesta de estandarización, movimiento de servicios, etc.

- Los comandos para conectarse a cada instancia están en el archivo "Inventario servicios-cuentas-*" de Drive.
- También hay un inventario de aplicaciones que creó @eduherraiz en el documento "Inventario python España - servicios y aplicaciones".

**Comment by dukebody** [comment]
Que yo recuerde, tenemos:
- Discourse
- Aplicación Django de gestión de socies
- Moodle pyladies Madrid

**Comment by dukebody** [comment]
Quien colabora necesita acceso. Nos puede pasar las claves públicas para que las metamos para acceder.

**Comment by dukebody** [comment]
La base de datos está en la misma instancia, no administrada por Scaleway.

**Comment by aalmiramolla** [comment]
Hola @dukebody,
Hemos estado hablando @alexgmin y yo, y hemos acordado el siguiente plan de acción para este issue:

- Obtener acceso al Bitwarden(?) para tener los credenciales de los servicios
- Investigar el Scaleway para ver qué máquinas virtuales tienen y que tiene cada una.
- Investigar otros servicios como DNS, Mailing, etc. (comprobar con Bitwarden)
- Crear un documento (Excel, doc., etc.) con todos los servicios, si tienen las credenciales guardadas en el Bitwarden, etc.

Si te parece bien, danos acceso a lo que corresponda y nos ponemos manos a la obra.

**Comment by aalmiramolla** [comment]
Hola @dukebody,
Hemos estado hablando @alexgmin y yo, y hemos acordado el siguiente plan de acción para este issue:

- Primero finalizar el issue #130.
- Discutir entre nosotros dos un ejemplo de estandarización y publicarlo en este issue.
- Esperar a que se apruebe, modifique, mejore, etc. el plan.
- Una vez aprobado, implementarlo.

**Comment by alexgmin** [comment]
Hola, @dukebody 

@aalmiramolla Ya hemos analizado las instancias y hemos visto que hay en cada una..

Tenemos varias opciones de como mantener y estandarizar todo, por listar algunas:
1. Montar un kubernetes con todo.
2. Migrar a un servicio de contenedores autogestionados, tipo AWS ECS o Scaleway Serverless Containers.
3. Ponerlo todo en una instancia dedicada grande en lugar de tener una para cada servicio, en Hetzner, por ejemplo.
4. Otras opciones

Luego para la base de datos de la página de socios también es contemplar si vale la pena tener algún servicio de managed postgres, tipo AWS RDS, Crunchydata, o las managed databases de Scaleway.

Nuestra idea es hacer una lista de las opciones que vemos, hacer un cálculo de cuanto costaría cada una con los servicios actuales y sus pros/contras.
Por ejemplo, el punto 2 es probablemente menos barata que 1 o 3, pero al mismo tiempo es probablemente la que menos mantenimiento requeriría con mantener los sistemas actualizados, que es también algo a tener en cuenta.

Así que las preguntas son:
- ¿Seguimos por esta ruta de hacer una lista de varias opciones?
- ¿Quien/quienes tendrían que tomar la decisión?
- ¿Hay algún factor que sea mucho más importante que el resto? Por ejemplo, es coste mensual más importante que el tiempo que luego requiera el mantenimiento?
- ¿Podemos contemplar otras opciones fuera de Scaleway?

**Comment by dukebody** [comment]
Hola @alexgmin .

Gracias por la investigación. Te contesto abajo.


>     ¿Seguimos por esta ruta de hacer una lista de varias opciones?

Sí, por favor.

>     ¿Quien/quienes tendrían que tomar la decisión?

Podéis tomarla vosotros, con autorización de la Junta si hay cambio significativo en el coste mensual.

>     ¿Hay algún factor que sea mucho más importante que el resto? Por ejemplo, es coste mensual más importante que el tiempo que luego requiera el mantenimiento?

Para mí el factor más importante es el bajo coste temporal de mantenimiento y sencillez. No importa pagar unos €s de más mensuales si así se simplifica todo, dentro de lo razonable. Por eso lo mejor es hacer la lista de alternativas con su coste y ver si la simplificación merece la pena el coste monetario extra.

>     ¿Podemos contemplar otras opciones fuera de Scaleway?

Sí, pero en ese caso, tened en cuenta los costes y riesgos de migración. A mi parecer, si no existen mejoras sustanciales en la simplificación del sistema, mejor no invertir el tiempo en migrarlo.

**Algunas consideraciones propias**
Así de primeras, la opción más lógica me parece meter todo en la misma instancia y así evitar tener que pagar y mantener cuatro. 

Montar un Kubernetes o similar para los pocos servicios y tan pocas necesidades de alta disponibilidad que tenemos me parece un esfuerzo de difícil justificación.

Por otra parte, tened en cuenta que Discourse es un sistema algo raro por como se configura e inicia, lo que puede crear algún problema con estandarizaciones en contentedores. Echadle un ojo a la instancia y veréis de lo que hablo.

**Comment by sincorchetes** [comment]
Buenas, siento haberme desvinculado tanto de la organización, me pasó este issue @alexgmin via Telegram.

Por lo que vi en el documento de infra:

### Hay 3 instancias corriendo y 1 en standby:
* moodle-pyladies: una instancia que pidieron las pyladies para tener una instalación de moodle
* discourse: una instancia donde se aloja el discourse de la asociación
* python-es: una instancia que solo sirve containers o webs estáticas. El servicio principal que tiene es el panel de socies.
* ye-olde-python-es: es una máquina que está en standby. Genera un coste marginal pero no es cero. Lo que pasa es que está usando una tarifa más antigua (y mejor) que las nuevas tarifas. Pero técnicamente se podría borrar, dado que ha estado parada muchos meses y nadie ha echado nada de menos

Creo que para las instancias estáticas simplemente sirve el GitHub Actions.
Para el moodle y discourse se puede contenirizar.
La máquina vieja se puede copiar con borg y mantenerla guardada en algún sitio como un S3 si no se ha echado en falta en este tiempo.

Kubernetes -> Coincidiría con @dukebody, sería tener una déuda altísima para lo que tenemos. Hay que crear las automatizaciones con Ansible, integrar el CI/CD no sé si con un Jenkins o GitHub Actions si lo permite, meter monitorización con Grafana, Prometheus...

Yo creo que simplemente una VPS en Hetzner, que sea una instancia con [Docker](https://www.docker.com/) o [Podman](https://podman.io/) (según se mire) valdría suficiente. Los pases se pueden hacer mediante un simple script y un servicio que compruebe que hayan cambios en el directorio de la máquina, o mirar de hacerlo con [GitHub Actions](https://docs.github.com/en/actions).

Tendríamos un snapshot de la máquina virtual, por si hay que reemplazar.
Se podría hacer backups de la máquina con el [Storage Box](https://www.hetzner.com/storage/storage-box) que da el propio Hetzner que no es caro y utlizando [Borg](https://www.borgbackup.org/) para las copias.

Para el enrutamiento, configuraríamos [Traefik](https://traefik.io/traefik/) con [Let's Encrypt](https://letsencrypt.org/) para dirigir las peticiones hacia los contenedores correspondientes.

Los yamls de configuración de la infra, la dejaríamos en un repositorio aparte.
Para la base del SO propongo utilizar [AlmaLinux](https://almalinux.org/) o [RockyLinux](https://rockylinux.org/) ya que son las distribuciones a nivel clónicas de RHEL siendo esta la más utilizada por la industria como base estable y sin tanto relleno (configuraciones adicionales, extras...etc) en la instalación de servicios.

**Comment by dukebody** [comment]
¡Hola @sincorchetes ! Gracias por un comentario con tanta información tan útil.

> python-es: una instancia que solo sirve containers o webs estáticas. El servicio principal que tiene es el panel de socies.
El panel de socies no es estático, es una app de Django. He hecho una propuesta a la Junta de sustituir este panel de socies por un Excel para simplificar y tener un servicio menos que migrar y mantener.

Me parece buena idea lo que planteas de un VPS en cualquier sistema cloud (Hetzner o lo que veáis mejor relación calidad, simplicidad y precio) y docker/podman.

No entiendo lo siguiente:

> Los pases se pueden hacer mediante un simple script y un servicio que compruebe que hayan cambios en el directorio de la máquina, o mirar de hacerlo con [GitHub Actions](https://docs.github.com/en/actions).

¿A qué te refieres con "los pases"?

> Para el moodle y discourse se puede contenirizar.

Al menos Discourse está containerizado ya. Pero tiene un sistema de containers propio que intenta simplificar pero es  bastante complejo. Ver https://github.com/discourse/discourse_docker.

Sobre backups, si con Borg es fácil estupendo, pero no sé si hay proveedores que automatizan la creación de backups sin tener que "instalarla" uno mismo. ¿Qué opinas?

Sobre enrutamiento, de nuevo lo que veáis mejor. Ahora mismo me consta que en algún sitio usamos https://caddyserver.com/, pero Traefik suena bien también. No se si están al mismo nivel o son proyectos totalmente distintos :sweat-smile:

SO el que queráis. Yo normalmente he utilizado Debian-based, pero si sabéis manejaros mejor con los tipo RHEL adelante.

¿Cómo tiramos esto adelante? ¿Podéis hablar entre @sincorchetes , @aalmiramolla  y @alexgmin y tomar una decisión en cuanto al stack? ¿Necesitáis más información de algún tipo?

Gracias de nuevo por el currazo.

**Comment by alexgmin** [comment]
Hola @dukebody 

La idea es hacer una llamada los 3 la semana del 21, en principio no necesitamos nada más que yo sepa.

Yo creo que con un poco de esfuerzo y organización podemos tenerlo todo organizado en septiembre.

Yo no soy muy fan de usar RHEL para este caso si la idea seria dockerizar todo, de forma que lo único que se usa del host sería docker y poco más.

Además de lo que se ha dicho ya, aporto algunas cosas que idealmente habría que considerar.

- La forma que actualmente accedemos a las instancias es mejorable, y en esto recomendaría migrar a algo que tenga consola ssh online, de forma que no tengamos que ir añadiendo public keys, y cada persona tenga su propia cuenta del servicio que use para todo, acceder al panel de administración de la infra y a las instancias. Y además podemos tener 2FA sin tener que usar un grupo de mail y buen auditing.
Se que AWS tiene esto, pero quizá es pasarse intentando buscar la perfección.
-  Otro tema a pensar es las 3 BDD como podemos montarlas bien si queremos tener menos gestión. Idealmente sería algún servicio autogestionado tipo RDS. 
El problema es que la instancia más pequeña de postgres ya subiría a alrededor de 10€ solo para eso. No obstante yo lo consideraria al menos para discourse, ya que migrar versiones de base de datos manualmente puede ser bastante trabajo. No obstante, es una opción a considerar ya que las BDD que tenemos contienen datos personales y la GDPR es estricta respecto a esto.
También hay que decir que la web de socios se podría migrar a un SQLite en lugar del postgres 9 (Creo que era esa versión) actual. 
- Respecto a backups preferiría una solución dada por el proovedor, para tener que tener menos conocimientos de cómo funciona el sistema de backups si algo falla y requerir menos mantenimiento.
- También, en el caso de la web de socios habria que considerar si se puede montar una CD.
- Y por último, cuando miramos el otro día vimos que la web de socios llevaba casi 2 semanas caída, así que convendria poner algún servicio de monitoreo basico. Para esto sugiero https://uptimerobot.com/ que la versión gratuita ya serviría.

**Comment by dukebody** [comment]
¡Hola!

Hemos estado hablando @alexgmin y yo por Telegram y hemos desviado la conversación un poco a cómo reducir al máximo el coste de mantenimiento de todo esto. Una de las conversaciones más productivas de la historia del IT de Python España jeje.

- El Django de socies estamos mirando en la Junta a ver si lo podemos pasar a Excel para tener una cosa menos que gestionar. Por lo que _de momento_ mejor no hacer nada y esperar a la decisión.
- Discourse (https://comunidad.es.python.org/) hemos visto que hay opciones hosted, como https://www.discourse.org/pricing, https://www.communiteq.com/discoursehosting/pricing/ o https://www.asplhosting.com/portal/en/alojamiento-especializado-discourse, que eliminarían completamente la necesidad de mantenerlo nosotros. 
- Moodle, la persona que lo está llevando no sabe si podrá hacerse cargo definitivamente de seguir con el curso en él (ahora mismo parece que no hay datos), y no lo sabrá hasta de aquí a 6 meses. Por lo que probablemente aquí también mejor esperar a esta decisión. Si es que sí lo queremos mantener, considerar encarecidamente uno hosted https://moodle.com/solutions/moodlecloud/.

Con esto, la única infra administrada que quedaría propia serían el registro de dominios y el DNS, con CDMon.

El resultado es que _es posible_ que no haya que montar ningún VPS, sistema de backups ni nada... Puede parecer un poco aguafiestas porque no se podría "cacharrear y jugar", pero esto mejoraría enormemente el futuro de la Asociación al eliminar la necesidad de gente que se encargue en el futuro de administrar los sistemas. 

Como bonus, curiosamente nos saldría todo incluso más barato, ya que ahora mismo pagamos unos 55€ al mes por Scaleway, y Moodle y Discourse hosted nos saldría por 20€ en la opción más barata. :tada: 

En cualquier caso, el trabajo que sí quedaría seguro sería:
- Migrar datos de web de socies.
- Migrar Discourse.

Comento todo esto con la Junta el lunes y os digo algo.

Como apunte final, usamos https://www.freshworks.com/website-monitoring/ para uptime monitoring. Acabo de añadir la actual web de socies.

**Comment by dukebody** [comment]
Tenemos el OK de la Junta Directiva para el plan de simplificación enunciado más arriba.

Es decir, mover la app de socies a un Excel y el servicio de Discord a hosted. El Moodle de momento no lo movemos, y si en unos meses no se ha hecho nada con él, lo eliminamos y punto.

@alexgmin @sincorchetes @aalmiramolla ¿Podemos crear issues con tareas/subtareas para realizar la extracción de datos y migración de los servicios actuales?

**Comment by dukebody** [comment]
Sobre migración, la máquina "ye-olde-python" creo que tiene algunos datos como fotos y tal. Lo mejor sería empaquetar lo que haya ahí y subirlo a Google Drive, donde tenemos muchos gigas de espacio gratuito.

**Comment by sincorchetes** [comment]
> Tenemos el OK de la Junta Directiva para el plan de simplificación enunciado más arriba.
> 
> Es decir, mover la app de socies a un Excel y el servicio de Discord a hosted. El Moodle de momento no lo movemos, y si en unos meses no se ha hecho nada con él, lo eliminamos y punto.
> 
> @alexgmin @sincorchetes @aalmiramolla ¿Podemos crear issues con tareas/subtareas para realizar la extracción de datos y migración de los servicios actuales?

Hola!

He creado este checklist, creo que está muy completo, os lo dejo por aquí: https://github.com/python-spain/asociacion/issues/149

¿Qué más falta?
* La máquina vieja es lo que comentaba @dukebody
* Moodle se queda como está
* Discourse hice el checklist

¿Se me pasa algo? ¿Tenemos un servidor de Discord también?

**Comment by alexgmin** [comment]
No existen servidores propios de Discord, todo lo hostea la la empresa Discord.

**Comment by sincorchetes** [comment]
Ah vale como lo había leído en el comentario.

**Comment by dukebody** [comment]
Perdón, me lío a veces como todo el mundo entre Discord y Discourse. No
tienen nada que ver :)

**Comment by aalmiramolla** [comment]
Ya se han creado las tareas como ha recomendado @dukebody, doy por cerrado este issue, ya que no hay nada que estandarizar como dijo @dukebody:
> Con esto, la única infra administrada que quedaría propia serían el registro de dominios y el DNS, con CDMon.
