### ISSUE TITLE
Migración de Discourse

### ISSUE THREAD

**Issue by sincorchetes** [python-spain/asociacion#149]
Creo que este checklist sería correcto, abierto para sugerencias.

1. Verificar la configuración de la base de datos para que no tengamos una sorpresa, (plugins, configuraciones...)
2. Subir una página en el hosting nuevo que apunte a un "En mantenimiento".
3. Modificar el dominio para que apunte a la web de mantenimiento.
4. Parar el servicio de Discourse
5. Realizar copia de seguridad del filesystem
6. Realizar copia de la base de datos
7. Subir los archivos al servidor
8. Importar la base de datos
9. Crear un subdominio que apunte al directorio de migración
10. Levantar el servicio
11. Probar que funciona el servicio (crear varios usuarios con diferentes roles e ir probando que todo vaya funcionando bien)
12. Actualizar el Discourse en este caso por si hay alguna actualización pendiente
13. Quitar la redirección a la página en mantenimiento
14. Redirigr las peticiones al Discourse

Faltaría:
* Planificar la parada:
   * Avisar a l@s usuari@s
   * Ver con quién contamos con la migración
   * Quién la va a llevar a cabo
   * Backup para ese día (si me toca a mí, que esté otra persona)
   * Tener todas las credenciales a la vista o tener todas las conexiones listas para empezar

**Comment by alexgmin** [comment]
Antes de esto también habría que contactar al proovedor de Discord que usemos, ya que probablemente saben más de como hacer una migración así y que hay que migrar.

@dukebody Entiendo que habría que hacer una lista de posibles proovedores. pero como hablamos por privado yo tiraría por [ASPL](https://www.asplhosting.com/portal/en/alojamiento-especializado-discourse) ya que hay relación previa con la empresa, y no hay mucha diferencia entre ellos y los otros que vimos como [Communiteq](https://www.communiteq.com/discoursehosting/pricing/). Y el hosting oficial era bastante más caro que las alternativas.

Lo principal además también sería ver que plan necesitamos, según cuanto espacio de disco se usa y número de visitas.

**Comment by dukebody** [comment]
Hola!

Haced una lista de posibles proveedores, sí  sin romperse la cabeza.
Importante comprobar que aceptan importar datos de otra instancia,
incluyendo todos los usuarios y mensajes.

Os puedo dar acceso de admin al Discourse la semana que viene para que
veáis espacio utilizado, plugins (creo que ninguno), visitas (pocas), etc.

Un saludo.

**Comment by dukebody** [comment]
Creo que Discourse tiene funcionalidades directas en la interfaz para guardar y restaurar backups. Echadle un ojo https://meta.discourse.org/t/move-your-discourse-instance-to-a-different-server/15721, https://meta.discourse.org/t/create-download-and-restore-a-backup-of-your-discourse-database/122710.

¿Necesitáis algún tipo de acceso especial a la instancia actual de Discourse para poder hacer estimaciones de espacio y volumen de tráfico? Si así, decidme vuestros usuarios y os doy los permisos pertinentes.

¿Alguna otra cosa que necesitéis para mover esto adelante?

**Comment by dukebody** [comment]
¡Hola! Nos equivocamos un poco, a la empresa https://www.asplhosting.com/portal/es/alojamiento-especializado-discourse no la conocemos. A la que conocemos es APSL, que es otra distinta. Perdón por la confusión.

Igualmente, el hosting de ASPL es el más barato de las opciones que hemos visto, y en el último mail que nos han enviado dan buena impresión y parecen profesionales.

Os paso estadísticas de visitas, directamente del admin de Discourse:
![image](https://github.com/python-spain/asociacion/assets/41953/6c18d235-f76b-48b4-8ad5-d4b10172681e)

![image](https://github.com/python-spain/asociacion/assets/41953/18cba81c-9517-46e0-9ac0-d0cf6b259202)

Avisad con lo que necesitéis para mover esto adelante, y ya nos quitamos una cosa de encima.

**Comment by sincorchetes** [comment]
La empresa a la que preguntamos nos incluye la migración, os comparto el correo:

```
Buenas días Álvaro,.

Gracias por contactar con nosotros.

Confirmaros que la migración entraría en el coste.

Lo que hacemos es montar un discourse con la última versión estable
desplegado sobre un nombre de dominio independiente
al discourse a migrar ([new.dominio.com](http://new.dominio.com/), [new001.dominio.com](http://new001.dominio.com/)).

A continuación os pedimos que hagáis un export del discourse actual para
que lo importemos en el nuevo, ajustamos y os pasamos
enlace para que lo podáis probar todo, ver qué tal va de rendimiento,
temas que queráis revisar, etc, todo antes de hacer el cambio de DNS.

Antes del cambio, os pediremos un último backup para hacer el último
exportado, y tras el cambio DNS, se vuelve a solicitar el certificado
Let's encrypt
para cubrir el nombre antiguo y el nuevo, de cara a tener https:// con
el nombre original.

Del migrado cubrimos las partes generales. A vosotros os dejaríamos
hacer los ajustes finos que necesitéis, ajustes de temas, iconos
colores, etc...
.y si algo se os engancha, o faltan librerías, componentes, etc,
podríais contar con nosotros para revisarlo.

En términos generales nos encargaríamos de desplegaros un discourse
totalmente funcional, bien conectado al nodo donde se despliegue,
con las herramientas que necesita para que sus componentes y ajustes
funcionen bien, migrar los datos, todo ello para dejarlo listo para entrar
en producción,  supervisión de seguridad y mantenimiento del sistema.

Sobre la versión del discourse, también podríamos desplegar alguna
específica que nos digáis. Esto lo revisaríamos para ver si es posible de
cara a confirmar, aunque en dichos casos, no hemos tenido problemas.

Cualquier duda contad con nosotros,
Un saludo,
```

He podido acceder al servidor y este es el esquema de consumo de espacio en disco:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        46G   29G   15G  67% /
/dev/vda15       99M  120K   99M   1% /boot/efi
```

La base de datos en PSQL ocupa 30mb comprimida.

**Comment by dukebody** [comment]
Genial. ¿Qué necesitáis para mover esto adelante?

**Comment by sincorchetes** [comment]
Después de ardúos trabajos con ASPL.es, hemos realizado correctamente la migración entre el día de ayer y hoy de manera éxitosa. Dejamos la máquina encendida durante una semana en caso de que haya que hacer rollback, y posteriormente la apagaremos y daremos por concluido este issue.

**Comment by sincorchetes** [comment]
Ya se ha apagado la máquina.
