### ISSUE TITLE
Hacer copia de seguridad de la máquina ye-olde-python-es

### ISSUE THREAD

**Issue by aalmiramolla** [python-spain/asociacion#150]
Como comenta @dukebody: https://github.com/python-spain/asociacion/issues/146#issuecomment-1677864564

Se debe de realizar un backup de los datos de dicha máquina y subirlos al GDrive de GT-IT

**Comment by aalmiramolla** [comment]
Realizado y guardado en Backups/20230817_backup_maquina_scaleway_ye-olde-python-es.tgz

**Comment by dukebody** [comment]
@aalmiramolla genial!!! Muchas gracias! 

Si os habéis asegurado de que está bien subido y que tiene toda la info importante de esa máquina, podéis eliminar el espacio de esa máquina en Scaleway. Lo podéis hacer como parte de esta issue u otra relacionada que creéis.
