### ISSUE TITLE
Mover la app de socies a un Excel 

### ISSUE THREAD

**Issue by aalmiramolla** [python-spain/asociacion#151]
_Originally posted by @dukebody in https://github.com/python-spain/asociacion/issues/146#issuecomment-1677859997_

**Comment by dukebody** [comment]
@aalmiramolla ¿tenéis claros qué pasos seguir para esto? ¿Necesitáis algún tipo de permisos o ayuda?

**Comment by alexgmin** [comment]
@dukebody Esto entiendo que debería hacerlo alguien que tenga permisos en la parte de datos de socies del Google Drive, ya que no tiene sentido ponerlo en la parte de IT. En principio el Django tiene función de exportar a CSV.

**Comment by dukebody** [comment]
@alexgmin Varias preguntas:
- ¿El export de CSV actual exporta todos los datos? ¿Se incluyen también los temas de pagos, o son otra tabla que no se exporta por defecto? Si no se incluye la tabla de pagos, ¿podríais exportar el SQL manualmente? Así luego la traspasamos a Excel.
- ¿Podríais exportar los datos al Drive de IT? Luego yo ya lo movería al de la Junta.

**Comment by alexgmin** [comment]
@dukebody 
En el Drive de IT hay ahora un dump sql y una carpeta con un csv para cada tabla. 
La mayoria de los CSV estan vacios o tienen datos que ya no son necesarios, estos son los relevantes:
- partners_partner -> Socies
- partners_notice -> Avisos de pago retrasado (Creo)
- partners_fee -> Pagos

**Comment by dukebody** [comment]
Genial, gracias! @ClaraMS se encargará de revisar esto y extraer los datos importantes, que copiaremos a una unidad separada. Entonces podremos borrar los datos que hay en el drive de IT, quizá guardando una copia de seguridad en algún sitio por unos meses, por si las moscas.

**Comment by ClaraMS** [comment]
Ya está exportado a Excel.
