### ISSUE TITLE
Recuperar contacto con O'Reilly

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/asociacion#18]
En su día @kikocorreoso consiguió que O'Reilly communities nos apoyara, y de hecho promocionó la PyConES de 2015:

https://us8.campaign-archive.com/?u=4babc22b9b74ea96c4cc6ca7a&id=6e9db720cc&e=2a3a27b8cb

No he podido encontrar si esto aún existe o no, pero en cualquier caso @mariocj89 se ofreció a tratar de retomarlo. Si ya no hay un programa continuado de apoyo a comunidades, entonces tendremos que conformarnos con pedirles descuentos para cada PyConES.

**Comment by kikocorreoso** [comment]
Los contactos del pasado (Github, O'Reilly, NoStarch,...) los transmití en sucesivas PyConES a otros organizadores. No sé si la nueva JD u organizadores ya los tendrán.

@mariocj89 si necesitas que te pase algunos correos me dices.

**Comment by mariocj89** [comment]
Gracias! Ayer escribí al contacto de la última pycones.
Si no responde te pido correos :)

**Comment by mariocj89** [comment]
Ofrecen un mes gratis de Safari para todos los miembros

**Comment by mariocj89** [comment]
Aprovado por la junta. Logo a poner en la web: ![orm_logo_box](https://user-images.githubusercontent.com/3709683/39517737-a82f7e9c-4df8-11e8-96e0-2517cf34e98d.jpg)

**Comment by Juanlu001** [comment]
¿No hay un logo de mejor calidad?

**Comment by mariocj89** [comment]
Este es el que nos ha proporcionado O'Reilly. Para como va a aparecer en la web creo que esta bien , si queremos uno con mayor resolucion puedo intentar pedirlo :/

**Comment by mariocj89** [comment]
Nos ha indicado oreilly que si queremos un acuerdo más a largo plazo y con condiciones de descuento de y similar miremos https://www.oreilly.com/partner/

Enviaré la propuesta

**Comment by mariocj89** [comment]
He solicitado el "partnership", deberiamos de tener una propuesta en 10 dias maximo

**Comment by mariocj89** [comment]
Tenemos respuesta de OReilly! 

A discutir en la proxima junta.

**Comment by mariocj89** [comment]
Some of the benefits:

Benefit | Description
-- | -- 
Conference Discount | 20% shareable discount code for passes to O'Reilly conferences. 
Access to O'Reilly Content | Each month we upload a variety of content (ebooks, reports, webcasts, video, excerpts, articles, etc.) and social media posts you can share with your community. Content is organized by topic area so you can share what is most interesting and applicable to your community.
O'Reilly Partner Rewards Program | Earn free conference passes. For every 3 uses of your code, earn a free pass to give away. 

Deliverables:
- [ ] Add logo to website
- [ ] Mailetter communication with the logo
- [ ] 3 shares in social media

**Comment by Juanlu001** [comment]
Ya hemos iniciado el proceso de registro y mandado el primer tuit con la información.

**Comment by mariocj89** [comment]
@Juanlu001 a gestionado el tema de las afilicaciones. Hemos enviado el correo con los codigos de descuento.
