### ISSUE TITLE
Formalizar los procedimientos que lleva a cabo la Secretaría de la Asociación

### ISSUE THREAD

**Issue by maigimenez** [python-spain/asociacion#22]
Existen distintos procedimientos rutinario que depende de la heurísitica de la persona que ejerce el papel de secretario de la asociación, como por ejemplo la gestión de las actas, la comunicación con los nuevos miembros de la asociación, ect. 
Sería intersante por lo tanto crear un recetario con estos procedimientos de modo que se simplifiquen las distintas tareas que llevará a cabo tanto la actual secretaría como aquellas personas que en el futuro ejerzan el cargo.

**Comment by dukebody** [comment]
@raulcd ¿te puedes encargar tú de esto?

**Comment by dukebody** [comment]
@raulcd ping

**Comment by dukebody** [comment]
La gran mayoría ya están como objetivo de 2021-T2 aquí: https://github.com/python-spain/asociacion/issues/131

@raulcd si hay algo más que haga secretaría adapta esta issue para cubrirlo.

**Comment by dukebody** [comment]
Cierro este ticket en favor de #131. Crearemos tickets individuales sobre cada procedimiento si es necesario.
