### ISSUE TITLE
Contactar con una gestoría

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/asociacion#23]
Hoy contacté con una gestoría para llevar las cuentas de la asociación y tratar de obtener el certificado de Utilidad Pública, que nos otorgaría exenciones fiscales.

**Comment by Juanlu001** [comment]
La gestoría con la que contactamos nos ha comunicado que no podrán asumirnos como clientes y nos han ofrecido varias alternativas.

**Comment by Juanlu001** [comment]
Por recomendación de Mayú Cooperativa hemos contactado con [Cooperativa Kinema](http://cooperativakinema.es/). A la espera.

**Comment by Juanlu001** [comment]
Mientras nos reunimos con Kinema, he mandado un email a asociaciones.org, asesoriafundacionesyasociaciones.es, debehaberasociaciones.com y weasesores.com, que eran los que salían en la primera página de Google. A la espera de respuestas.

**Comment by Juanlu001** [comment]
Ya tenemos presupuesto de dos de las mencionadas arriba, y otra nos ha mandado un cuestionario a rellenar.

**Comment by maigimenez** [comment]
¡Todo funcionando con la gestoría!
