### ISSUE TITLE
Investigar la posibilidad de usar GSuite para la Asociación

### ISSUE THREAD

**Issue by maigimenez** [python-spain/asociacion#25]

**Comment by maigimenez** [comment]
@vterron ha localizado los pasos que hay que dar:
- [Crear una cuenta de Google para Organizaciones sin Ánimo de Lucro](https://www.google.com/nonprofits/eligibility/)
- [GSuite para Organizaciones sin Ánimo de Lucro]( https://support.google.com/nonprofits/answer/3367223?visit_id=636758891487255252-2873784940&rd=1)

**Comment by dukebody** [comment]
Esto ya lo tenemos en marcha, después de casi dos años :D  He registrado Python España como organización en TechSoup Spain, subido una serie de documentos, y ahora estoy esperando a ver si lo validan y podemos utilizar GSuite para el correo y documentos.

**Comment by dukebody** [comment]
Ya tenemos GSuite de la asociación, con el mail, grupos y documentos. Mil gracias a @XaviTorello por el curro que le ha metido a esto. ¡Lo damos por cerrado!
