### ISSUE TITLE
Kit de merchandising para eventos

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/asociacion#26]
Nos preguntan por el canal de Telegram:

> ¿podría pediros a otras comunidades colaboración? ¿Materiales para el taller?, ¿pegatinas de vuestras comunidades si tenéis?

[Enlace](https://matrix.to/#/!kRvcHoRgNNnCELukDB:matrix.org/$153908769911990eTRld:t2bot.io)

No es la primera vez que nos lo piden, y de hecho se presenta la oportunidad de aprovecharlo en el PyDay Tenerife 2018. Recordemos que tenemos la tienda FreeWear:

https://www.freewear.org/?page=list_items&org=PythonEspa%C3%B1a

**Comment by XaviTorello** [comment]
Sobre los stickers, se podría llegar a hacer tiradas "bestias" por un precio relativamente bajo si apostamos por un formato reducido.

**Comment by mariocj89** [comment]
Los stickers es fácil, podemos comprar un palé y darlos en pycons/pycenas. 

En cuanto a los totems, recomendaría un roll-up para que sea mas fácil transportarlo y guardarlo, pero le daría mucha profesionalidad a los eventos.

Lo incluyo para la proxima junta.

**Comment by XaviTorello** [comment]
Genial!

**Comment by mariocj89** [comment]
Hablado en la reunion de Noviembre.
Aprobado hacerlo con dos grupos piloto.

- 2 Rollup con la web, twitter y logo
- 1000 pegatinas de la asociación

Pendiente del diseño.

**Comment by maigimenez** [comment]
Mabel los enviará.

**Comment by Juanlu001** [comment]
El rollup sigue en Alicante pero está controlado. Creo que esta tarea se puede cerrar.

**Comment by dukebody** [comment]
¡Hola! Entiendo que los dos rollups y las etiquetas se han distribuido a Python Alicante y a Python Girona.

Si este ticket es sólo para estos dos podemos cerrarlo, pero creo que en realidad la tarea sería definir un proceso por el cual una comunidad puede solicitar a Python España merchandising de eventos.  Ver https://github.com/python-spain/asociacion/wiki/Apoyo-de-Python-Espa%C3%B1a-a-comunidades-locales

**Comment by XaviTorello** [comment]
Cierro issue, seguimos en #58 

Gracias @all! :beers:
