### ISSUE TITLE
Lista de contactos (¿CRM?)

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/asociacion#28]
Los registros de patrocinadores de PyConES anteriores están desperdigados en admins de Django de difícil acceso (no hay "recordar contraseña"), boards de Trello y bandejas de entrada. Sería interesante tener esto centralizado en algún sitio.

**Comment by marcosgabarda** [comment]
Cómo estoy ampliando el backend que tenemos ahora para gestionar los socios, se podía ampliar para tener también la gestión de los patrocinadores

**Comment by Juanlu001** [comment]
Voy a reunir los contactos de años anteriores en una hoja de cálculo aunque sea.

**Comment by Juanlu001** [comment]
...la he encontrado :tada:

**Comment by dukebody** [comment]
Duplicada de https://github.com/python-spain/asociacion/issues/17
