### ISSUE TITLE
Evaluar gestores de contraseñas para equipos

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/asociacion#3]
Opción más prometedora: https://github.com/passbolt/passbolt_api/ (PHP). @aaloy propuso otras, y lo hablé con @gnuites también. @pablogsal hay que ver cómo alojamos esto.

**Comment by Juanlu001** [comment]
| Nombre   | Código fuente                               | Lenguaje | Licencia   | Contribuidores | Última versión                                                                  |
|----------|---------------------------------------------|----------|------------|----------------|---------------------------------------------------------------------------------|
| Passbolt | https://github.com/passbolt/passbolt_api/   | PHP      | AGPL-3.0   | 357            | 2.0.5 hace 1 día                                                                |
| sysPass  | https://github.com/nuxsmin/sysPass          | PHP      | GPL-3.0    | 14             | 2.1.15 hace 8 meses (3.0-beta hace 1 mes y medio)                               |
| TeamPass | https://github.com/nilsteampassnet/TeamPass | PHP      | GPL-3.0    | 13             | 2.1.26-patch-1 hace año y medio (2.1.27.12 hace 7 días marcada como prerelease) |
| PSONO    | https://gitlab.com/psono/psono-server       | Python   | Apache 2.0 | 3?             | 1.4.2 hace 1 mes                                                                |
| Passit   | https://gitlab.com/passit/passit-backend    | Python   | AGPL-3.0?  | 5?             | 1.0.0 hace 6 meses                                                              |
| PASSY    | https://github.com/PASSYpw/PASSY            | PHP      | GPL-3.0    | 2              | 2.0.4 hace 6 meses                                                              |

**Comment by Juanlu001** [comment]
Más alternativas:

* @gnuites propuso keybase.io, pero aunque es muy interesante parece que el servidor es cerrado.
* Podríamos tener un repositorio privado en https://gitlab.com/PythonES o en un servidor nuestro con las claves. No sé si es mejor o peor que alguna de las opciones de arriba.

**Comment by mariocj89** [comment]
👍 a cualquiera de las dos ultimas, priorizando el "solución hosteada". Todo lo que tengamos que montar es trabajo para el resto de la vida.

- Keybase.io (acabo de probarlo, tiene buena pinta para esto). Como dices el backend no es open source, los clientes lo son.
- Repo en gitlab: un poco "meh" pero vale. GitLab es opensource

**Comment by Juanlu001** [comment]
También tenemos esta solución hosteada, open source y stateless: https://lesspass.com/ Habría que compartir con la Junta la clave maestra.

**Comment by Juanlu001** [comment]
En la JD de hoy nos hemos decantado por usar un archivo KeePassXC compartido en una carpeta Dropbox, que es lo que han propuesto en Python Barcelona.

**Comment by Juanlu001** [comment]
Ya está compartido, cerrando.
