### ISSUE TITLE
¿Pagar Mailchimp?

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/asociacion#30]
La versión actual nos viene limitando hace un tiempo el número de usuarios. Revocar los antiguos y dar de alta a nuevos ya no sirve.

Si se decide pagar, se podría aprovechar el [descuento para non-profits](https://mailchimp.com/help/about-mailchimp-discounts/#Nonprofit_discount).

Lo necesita el grupo de trabajo de la PyConES cc @bameda 

Se habló en su día con la junta anterior con prisas y estaba informalmente aprobado pero habría que dar el paso.

**Comment by Juanlu001** [comment]
Por cierto, por alguna misteriosa razón @Zuriich está de "owner". Ya le he pedido que me lo transfiera.

**Comment by Juanlu001** [comment]
![Screenshot_2020-01-30 Users Mailchimp](https://user-images.githubusercontent.com/316517/73436527-f7aa5e80-434a-11ea-9aea-a989f3a0117d.png)

**Comment by dukebody** [comment]
@bameda , ¿necesitamos Mailchimp? Si hay que pagarlo se paga, pero me gustaría entender un poco para qué se usa en concreto.

**Comment by dukebody** [comment]
Estamos usando Mailjet ahora.
