### ISSUE TITLE
Traspaso de permisos de repos de GH a nueva Junta

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#31]
Seguramente se pueda hacer cambiando los usuarios en los "Teams".

**Comment by Juanlu001** [comment]
Hecho :wink: Cuando hagamos el traspaso oficial (#33) y tengas la firma electrónica (#34) me quito yo.

**Comment by dukebody** [comment]
¡Gracias!

He visto que nos has añadido al [equipo de Junta Directiva](https://github.com/orgs/python-spain/teams/junta-directiva/repositories), pero este equipo no tiene permisos de admin sobre todos los repos, que necesitaremos en el futuro si queremos hacer cualquier cambio en la configuración de los repos. 

¿Sabes cómo hacer el traspaso total y darnos permisos de admin?

**Comment by Juanlu001** [comment]
Acabo de dar permiso de admin a los repos que ya tenía el team. Cómo hacerlo para todos de manera automática no lo tengo claro.

Te iba a poner de Owner de https://github.com/orgs/python-spain/ pero veo que no tienes la 2FA activada :) https://freeotp.github.io/

**Comment by dukebody** [comment]
¡Genial!  Acabo de añadir 2FA a mi cuenta.

**Comment by Juanlu001** [comment]
El nuevo presi ya es Owner de la organización :tada:
