### ISSUE TITLE
Cambio composición Junta en el Registro Nacional de Asociaciones

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#33]
El proceso está descrito en https://github.com/python-spain/wiki/wiki/Proceso-cambio-Junta-Directiva#inscripci%C3%B3n-en-el-registro-nacional-de-asociaciones

* [x] Publicar y firmar acta elección nueva JD @maigimenez  
* [x] Solicitar en el RNA la inscripción de la nueva JD @dukebody

**Comment by dukebody** [comment]
He comenzado a rellenar la documentación mencionada en http://www.interior.gob.es/ca/web/servicios-al-ciudadano/asociaciones/inscripciones-registrales-de-las-asociaciones/inscripcion-de-la-identidad-de-los-titulares-de-la-junta-directiva-u-organo-de-representacion. La comparto con el resto de la Junta por Google Docs, acabamos de poner todos los datos, firmamos todo y presento la solicitud. :)

**Comment by dukebody** [comment]
Actualización: ya tenemos los papeles rellenados y sólo nos faltan las firmas. Hemos contactado con la asesoría y nos hará el trámite. El contacto con la asesoría lo lleva @marcosgabarda .

**Comment by dukebody** [comment]
@marcosgabarda Ya están todos los datos de la nueva JD para el certificado. ¿Cómo va el trámite de la asesoría?

**Comment by dukebody** [comment]
Los documentos a firmar ya están, pero hace falta que los firme toda la Junta entrante y saliente. Hay dos posibilidades:
1. Usar Adobe Sign. Se puede firmar directamente con una imagen, no necesita certificado digital. Hay una versión de prueba de 14 días. Entiendo que si no somos rápidos nos puede caducar.
2. Usar el cliente [AutoFirma](https://firmaelectronica.gob.es/Home/Descargas.html). Necesita certificado digital de todo el mundo.

En los dos casos el proceso es que el documento se va enviando a cada persona que lo tiene que firmar y se va firmando en cadena.

Preguntamos a la gente de las dos Juntas si tienen certificado digital para firmar y a partir de ahí tomamos una decisión.

**Comment by dukebody** [comment]
@marcosgabarda está recopilando las firmas de toda la gente de las Juntas saliente y entrante. Vamos marcando aquí a medida que las vamos recopilando.

Entrante:
* [ ] Israel Saeta
* [ ] Xavi Torelló
* [ ] Raúl Cumplido
* [ ] Marcos Gabarda
* [ ] Maria Antònia Tugores
* [ ] Yamila Moreno
* [ ] David Barragan

Saliente:
* [ ] Juan Luis Cano
* [ ] Mario Corchero
* [ ] Mai Gimenez
* [ ] Marcos Gabarda
* [ ] Mabel Delgado
* [ ] Pablo Galindo

**Comment by yamila-moreno** [comment]
Mi firma debería tenerla pues ya se la mandé, ¿puedes confirmar, @marcosgabarda ? ¿te la mando de nuevo?

**Comment by marcosgabarda** [comment]
@yamila-moreno tu firma la tengo!

**Comment by dukebody** [comment]
La solicitud ya la ha presentado la asesoría ante el RNA. Dejamos esta tarea abierta hasta que nos notifiquen que se ha hecho el cambio. :)

**Comment by dukebody** [comment]
@marcosgabarda si los tienes, ¿puedes subir al Drive de la JD a "Documentacion > Docs cambio de Junta 2020" los documentos que hemos presentado? Así los tenemos para referencia de futuras generaciones.

**Comment by dukebody** [comment]
@marcosgabarda ninguna noticia del tema del registro, ¿no?

**Comment by marcosgabarda** [comment]
No, no hay noticias al respecto aún.

**Comment by marcosgabarda** [comment]
Pregunté a la asesoría como estaba este trámite, y me han contestado esto:

> El cambio de junta se presentó en el registro el 12 de marzo. El registro puede tardar hasta 3 meses en resolver pero actualmente todos los plazos de la administración están suspendidos y no están trabajando en el registro.

Que es normal en realidad, así que toca tener paciencia :(

**Comment by XaviTorello** [comment]
@marcosgabarda@20/08/20:
> hola! tengo el placer de comunicaros que ya se ha oficializado el cambio de junta! desde la fecha del 6 de agosto (la persona de la asesoría estaba de vacaciones y lo ha visto ahora cuando ha vuelto) somos ya oficialmente la nueva junta de Python España 😊

Cierro esta issue, gracias @marcosgabarda y a todos los demás por el esfuerzo :)

**Comment by astrojuanlu** [comment]
:heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes: ¡¡Por fin!! Enhorabuena y gracias a @marcosgabarda y a todos los que lo han hecho posible :muscle:
