### ISSUE TITLE
Obtener firma electrónica representante 

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#34]
Bloqueada por https://github.com/python-spain/asociacion/issues/33

Cómo hacerlo en https://github.com/python-spain/asociacion/wiki/Proceso-cambio-Junta-Directiva#firma-electr%C3%B3nica-de-representante:
* [ ] Obtener certificado JD en el RNA @dukebody 
* [ ] Pedir firma digital en AEAT @dukebody

**Comment by Juanlu001** [comment]
> Estimado/a Sr/a CANO
>
> Le informamos que el Certificado FNMT de Representante de Persona Jurídica con NIF del representante 52004994Q, NIF de Entidad G86766821 y número de serie [redacted] caducará el próximo día 05/04/2020

**Comment by dukebody** [comment]
Hola @Juanlu001 ! El problema no es sólo que te caduque a ti, sino que en principio tu firma ya no es válida como representante de la asociación. Es decir, ahora mismo no sé si hay alguien con la capacidad legal de firmar, al menos electrónicamente, en nombre de la asociación.

Tenemos que notificar el cambio de Junta en el RNA cuanto antes.

**Comment by dukebody** [comment]
¡Ya la tenemos!
