### ISSUE TITLE
Acceso a buzones de email oficiales

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#37]
Necesitamos acceso a los buzones oficiales de presidencia@es.python.org, etc.

@Juanlu001 ha mandado ya un mail a Jesús Cea solicitando el traspaso para Presidencia, Vicepresidencia y Secretaría.

Esta tarea es urgente porque es nuestro canal de comunicación oficial de cara al exterior.

**Comment by XaviTorello** [comment]
`vicepresidencia@` ok!

gracias @jcea :beers:

**Comment by dukebody** [comment]
Yo ya tengo acceso a mi buzón también. Marco el issue como resuelto y, si alguien tiene algún problema, que lo reabra.
