### ISSUE TITLE
Cambio de admins canales Telegram

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#39]
Hay que cambiar los admins/owners de los canales de:

* [ ] Socios
* [ ] General

Esto lo pueden hacer: @Juanlu001, @mabeldelgadob , @maigimenez , @mariocj89 , @marcosgabarda probablemente.

**Comment by Juanlu001** [comment]
¿Quiénes quieren ser los nuevos owners?

**Comment by Juanlu001** [comment]
He puesto a toda la JD como estaba antes. El owner no puedo dejar de ser yo porque creé el grupo. ¡Cerrando!
