### ISSUE TITLE
Estudiar nuevos canales de comunicación

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/asociacion#4]
De la candidatura:

> * Plataforma tipo "foro" para dinamizar las listas de correo actuales.
> * Estudio de una nueva plataforma con múltiples canales para la comunidad (Slack/Matrix/Similar) que permita diferentes hilos de comunicación (Empleo/General/Offtopic/etc).

**Comment by Juanlu001** [comment]
@eduherraiz ha montado una instalación de Zulip (https://github.com/zulip/zulip) para experimentar. En cualquier caso, creo que deberíamos evaluar las soluciones en base a:

* **Aplicabilidad**: ¿queremos soluciones diferentes para sustituir las listas de correo y el chat de Telegram, o buscar una que sirva para ambas?
* **Audiencia**: ¿cómo funciona la herramienta para comunidades abiertas? ¿tiene herramientas de moderación, control de SPAM?
* **Familiaridad/Popularidad**: ¿es la herramienta ya conocida para nuestra audiencia?
* **Licencia**: ¿es la herramienta open source?
* **Actividad**: ¿está la herramienta bien mantenida en la actualidad?

Y posiblemente se os ocurran otros. ¿Opiniones?

**Comment by pablogsal** [comment]
Creo que debemos actuar con cautela puesto que es posible que la gente no quiera instalar/usar un cliente que solo van a usar para nuestra asociación (especialmente si se trata de un cliente de chat, IMHO).

**Comment by Juanlu001** [comment]
La opción más cautelosa es no hacer nada y mantener el status quo :) Hay que ver si cambiar de plataforma soluciona estos dos problemas:

1. El canal de Telegram está muerto de éxito y ya no escala. Hay +1300 miembros ahora mismo, de los cuales 14 copan el 50 % de la actividad en el último mes, por no hablar de que no hay forma de separar preguntas para gente que está aprendiendo y no sabe nada de discusiones más complicadas.
2. Las listas de correo están muertas. Ahí no hay mucho que medir.

Para el problema 2, cualquier cosa que ofrezcamos va a ser mejor o igual que lo que hay ahora (actividad nula). El problema 1 es más delicado y requiere pensar un poco.

La respuesta a la pregunta puede ser "mejor no cambiar nada", pero en todo caso hay que hacerla. Y también puede ser "usemos Slack", en cuyo caso tendrá mi voto particular en contra pero creo que eso no impide que otros opinen de manera diferente.

**Comment by pablogsal** [comment]
Creo que para el primer punto la clave es minimizar la fricción para adoptar lo que sea que usemos. Por mucho que me gustaría usar Zulip o matrix o similar creo que es mala idea puesto que muy poca gente va a utilizar estos canales salvo que ya los estén usando.

El punto dos, usemos lo que usemos hay que tener en cuenta que hay que hacerlo inteligentemente o se va a ver totalmente eclipsado por el chat.

**Comment by maigimenez** [comment]
La JD ha comenzado a abordar el asunto en el [acta](https://github.com/python-spain/actas/blob/master/acta-2018-05-01.rst) del 1 de Mayo de 2018, pero se desarrollará con más profundidad en un próximo monográfico.

**Comment by maigimenez** [comment]
Discourse montado por @pablogsal y en pruebas 💯
