### ISSUE TITLE
Cambio de email de contacto cuenta O'Reilly

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#40]
Necesitamos darle el correo de la persona con la que se deben comunicar.

Queremos cambiarlo a un mail oficial tipo junta@es.python.org. @mariocj89 y @XaviTorello lo llevan.

**Comment by dukebody** [comment]
A la espera de tener acceso a los buzones oficiales para no tener que estar cambiando esto con cada Junta.

**Comment by XaviTorello** [comment]
Solicitud de cambio de contacto realizada por @mariocj89.

O'Reilly está a la espera de que creemos una cuenta gratuita en su site, ya hemos avisado que lo haremos tan pronto tengamos acceso a las cuentas de email de la Asoc.

La idea es utilizar el alias "junta@".

**Comment by XaviTorello** [comment]
Cuenta "contacto@" creada. A la espera de confirmación por parte de O'Reilly para dar por cerrado el traspaso.

**Comment by XaviTorello** [comment]
Confirmado, se ha podido migrar correctamente la cuenta de tipo partner a `contacto@`.

Gracias @mariocj89 :)
