### ISSUE TITLE
Contratar seguro de responsabilidad civil

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#42]
Por ley la organización de un evento es la responsable civil del mismo, por lo que está obligada contratar un seguro de responsabilidad civil que cubra los eventos.

Desde Python España @Juanlu001 ya pidió 3 presupuestos, que están en el buzón de mail de Presidencia, pero hay que elegir aseguradora y tirarlo hacia adelante. Yo me encargo de hacer un resumen de las opciones y tomamos una decisión en la próxima Junta.

**Comment by dukebody** [comment]
Ver https://www.segurcoworking.com/normativa-que-afecta-a-un-organizador-de-eventos/#Contratar_seguro_de_responsabilidad_civil_de_organizador_de_eventos

Los prespuestos están en el Drive de la Junta.

**Comment by dukebody** [comment]
Después de echar un ojo al enlace anterior he pedido presupuesto para lo siguiente:
- Un seguro anual de hasta 601.000€ asegurados para cualquier evento de hasta 300 personas en cualquier sitio del Estado. (excepto en La Rioja que se necesitaría sin franquicia, pero eso lo podríamos contratar aparte).
- Un seguro de 3-4 días de duración específico para la PyConES de hasta 1000 personas.

Voy actualizando.

**Comment by dukebody** [comment]
Tengo un presupuesto casi final con la mediadora Arç Cooperativa. Cuando lo tenga todo aviso a la gente.

**Comment by dukebody** [comment]
A todo esto, @bameda , ¿puedes preguntar si el seguro de Responsabilidad Civil de la propia UGX cubriría el evento? ¿En qué condiciones?

**Comment by dukebody** [comment]
He preguntado a la asesoría legal qué condiciones tiene que cumplir el evento para que el seguro los cubra. Parte de mi email:

> ¿qué requisitos debe cumplir este evento para que lo cubra en su totalidad el seguro de RC de Python España?
> - ¿Tiene que constar Python España como entidad organizadora única?
> - ¿Es suficiente que conste como co-organizadora? En este supuesto, ¿se compartiría de alguna manera la responsabilidad entre todas las personas físicas y jurídicas que co-organicen?
> - ¿Cómo de claro y evidente para todos los asistentes debe estar que Python España organiza o co-organiza? ¿Es necesario que en el anuncio del evento ponga explícitamente que Python España organiza?

¡Seguimos!

**Comment by dukebody** [comment]
Ya tenemos el seguro. :)

**Comment by astrojuanlu** [comment]
:tada:
