### ISSUE TITLE
Revisar dónde llegan los mails de alta@es.python.org

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#46]
Esta dirección es la que se usa para la inscripción de nuevos socios. Si se implica a Tesorería y Secretaría en el proceso, quizá convendría que el mail llegase a ambos. Comprobar.

**Comment by raulcd** [comment]
Comprobado, ahora mismo llegan a los correos personles del tesorero y la anterior secretaria. Se ha pedido redirección. @XaviTorello si recibes info de mails comenta aquí, please.

**Comment by XaviTorello** [comment]
Con el nuevo servicio de email lo hemos solucionado definiéndolo como un alias de `junta@`, de forma que llegarán a toda la Junta Directiva.

Cerramos issue, gracias a todos :beers:
