### ISSUE TITLE
Publicar documento de ayuda a comunidades locales

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#49]
En la última reunión @atugores presentó un borrador de documento de ayuda a comunidades locales, basado en parte https://github.com/python-spain/asociacion/wiki/Apoyo-de-Python-Espa%C3%B1a-a-comunidades-locales , que se aprobó con modificaciones.

Tareas:
- [x] revisar el documento y generar una redacción final @atugores 
- [x] publicar esta información: la constatamos en github y le damos publicidad en nuestros canales: discourse, web, twitter, telegram. @dukebody y @bameda 
- [x] Añadir 2-3 ejemplos de qué tipo de cosas que se han pedido a la asociación. @marcosgabarda 
- [ ] al hilo de esto, generar unos presupuestos anuales (que faciliten gestionar las ayudas económicas) Ver https://github.com/python-spain/asociacion/issues/44 @marcosgabarda

**Comment by yamila-moreno** [comment]
@atugores Hemos cerrado una versión del documento. Cuando puedas, ponlo como .rtf en el repo de la asociación para que le demos difusión. ¡Gracias!

**Comment by XaviTorello** [comment]
Validado en la reunión de seguimiento de hoy, cerramos issue.

Gracias @all :+1:
