### ISSUE TITLE
Transferir cuenta de Twitter a contacto@...

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#50]
Actualmente está ligada a una cuenta de mail personal, lo que dificulta su gestión comunitaria.

**Comment by dukebody** [comment]
@bameda esto ya está, no?

**Comment by dukebody** [comment]
@bameda ping

**Comment by dukebody** [comment]
@bameda esto se hizo?

**Comment by dukebody** [comment]
@bameda el mail aún es uno tuyo. @JimenaEB Podrías cambiarlo a contacto@.... o creamos uno específico para Twitter?

**Comment by bameda** [comment]
> @bameda el mail aún es uno tuyo. @JimenaEB Podrías cambiarlo a contacto@.... o creamos uno específico para Twitter?

Igual mejor un alias, para que vaya al mismo sitio pero se pueda filtra, my two cents

**Comment by bameda** [comment]
elegid un email y yo me encargo

**Comment by dukebody** [comment]
He decidido utilizar un grupo por imitar lo que hacemos con otras herramientas como Streamyard o Eventbrite. He creado el grupo twitter-python_es@es.python.org y os he invitado a @JimenaEB y a ti @bameda 

@bameda avisa cuando tengas el cambio hecho porfi.

**Comment by bameda** [comment]
Pues estaré al tanto, parece que ahora mismo no puedo cambiarlo
![image](https://github.com/python-spain/asociacion/assets/877218/3e81792a-e655-4bd6-a358-459559e900e1)

**Comment by bameda** [comment]
Done
