### ISSUE TITLE
Ayuda para mejorar web en Django para ayudar a hospitales (COVID)

### ISSUE THREAD

**Issue by jantoniomartin** [python-spain/asociacion#52]
Buenas noches.

Anoche inicié [este repositorio](https://github.com/jantoniomartin/hospitales-covid19) como propuesta de herramienta para el Forum A.I.R.E., que está intentando organizar las necesidades de recursos para hospitales por la emergencia del Coronavirus. En principio se trata de llevar un inventario de necesidades por centro, para contactar con proveedores que puedan cubrirlas.

La herramienta, muy sencilla de momento, está hecha sobre Django y se puede ver en http://strider.webfactional.com

La necesidad se comenta en [este hilo](https://foro.coronavirusmakers.org/index.php?p=/discussion/156/software#latest). Actualmente la gestión se está haciendo en un [excel en Drive](https://docs.google.com/spreadsheets/d/120GGCsPH5h7_HSL08qXou_r3mRT8tn5cFi35sjs0Zi0/edit#gid=0), no demasiado estandarizado.

He contactado con uno de los administradores del forum A.I.R.E. y habrá que modificar y mejorar la web con urgencia, por lo que me gustaría pediros ayuda para ello.

Edito: [más información](https://ayudacoronavirus.blogspot.com/).

Gracias y un saludo,
José Antonio

**Comment by astrojuanlu** [comment]
Gracias @jantoniomartin, he difundido esto en el Telegram de Socios y en el grupo general de Python España.

**Comment by danim47c** [comment]
Buenas, soy Daniel, un estudiante español.
Me encantaría poder ayudaros con este proyecto. Llevo en cuarentena unos días y no encuentro mejor manera de invertir mi tiempo que ayudando a los que están dando la cara para salvarnos.

**Comment by jespino** [comment]
Buenas, suena muy interesante, si pudieras ir creando tickets de cosas que
hacen falta en github la gente que quisiera participar podría ir sacando
trabajo adelante y haciendo Pull Requests.

Yo personalmente no tengo tiempo para implicarme en el proyecto de manera
activa, pero si para resolver tickets sueltos en la medida que mi trabajo
me deje hacerlo.

Un saludo.

**Comment by jantoniomartin** [comment]
Gracias a todos. Aclaro que no tengo muy claras las gestiones que se están haciendo desde A.I.R.E. con hospitales y proveedores.
Voy a intentar que desde el foro me vayan poniendo _issues_ con las necesidades que tengan para ir implementándolas.

**Comment by jespino** [comment]
Otra cosa, el proceso de setup no es trivial, hay que añadir el "site"
añadir el settings.py, hay que usar una variable de entorno para el SECRET.
Tengo una pequeña propuesta que puedo añadir al readme para que sea mas
facil montar el entorno.

Otra cosa que a mi me ayuda a entender mejor el contexto de la aplicación
es generar datos aleatorios de ejemplo, de manera que la base de datos esté
poblada y se pueda ver la aplicación funcionando de verdad (o parecido a
como sería de verdad).

Un saludo.

**Comment by jantoniomartin** [comment]
Al parecer hay una aplicación que va más avanzada que la que yo inicié. Si a alguien le interesa, puede preguntar en https://t.me/TICparaBienChat.

Gracias a todos.

**Comment by dukebody** [comment]
¡Hola! Entiendo que esto ya se está gestionando por otro sitio. @jantoniomartin si necesitas difusión de esto puedes escribir en https://comunidad.es.python.org/ y le hacemos algún tweet.
