### ISSUE TITLE
Kit Pysurfing entre comunidades pythonicas

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#54]
Gente que se proponga para dar charlas en otras comunidades. Proporcionamos mecanismos contacto, consejos sobre gastos. 
Puede venir bien para ampliar círculos de +gente ponente en algunas comunidades.
Puede servir para organizar desplazamientos (alguien de Segovia va al meetup de Zamora) o para Meetups en remoto por ejemplo.

**Comment by astrojuanlu** [comment]
Yo antes de la pandemia me pasé por Salamanca y por Mallorca, y seguro que hay más gente que ya ha hecho PySurf :)

**Comment by manugarri** [comment]
no tienen que ser charlas en persona, no? Se pueden hacer conexiones.

**Comment by XaviTorello** [comment]
> no tienen que ser charlas en persona, no? Se pueden hacer conexiones.

Para mí tiene sentido, y más ahora 👍

**Comment by dukebody** [comment]
Por referencia, https://comunidad.es.python.org/t/grupo-de-intercambio-de-ponentes-para-charlas-inter-comunidades/475.

**Comment by dukebody** [comment]
He vuelto a avisar de esta posibilidad en el Telegram de comunidades. Se puede seguir usando https://comunidad.es.python.org/t/grupo-de-intercambio-de-ponentes-para-charlas-inter-comunidades/475/10 para conectar.
