### ISSUE TITLE
Presentación de comunidades locales

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#56]
Entrevista a cada grupo local para que nos digan qué actividades han hecho ese año y poder presentarlas entre ellas. Enviar documento para que cada comunidad lo rellene y publicarlo en el blog.

**Comment by dukebody** [comment]
Esto conecta bastante con #64 .

**Comment by dukebody** [comment]
Nos hemos reunido ya con Python Sevilla, Python Vigo y Python Canarias. Estoy intentando programar una reunión aproximadamente cada semana para cubrir todas las comunidades en un tiempo razonable. ¡Ojalá cuando acabemos la ronda hayan surgido nuevas comunidades que contactar! :D

**Comment by dukebody** [comment]
En principio sólo nos faltan Mallorca, Girona y Alicante.

**Comment by dukebody** [comment]
Cierro porque, aunque no hemos hecho reunión formal con estas tres últimas, si conocemos bien gente en todas ellas y tenemos confianza para tirar cosas adelante.
