### ISSUE TITLE
Ofrecer infraestructura a comunidades locales

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#60]
Hace falta sistematizar cómo se gestiona la infra actual.
El objetivo es que las comunidades locales puedan disponer de la infra de la asociación si lo necesitan, para facilitar su labor.

**Comment by dukebody** [comment]
Esto ya lo estamos haciendo. Por ejemplo dando infra a PyLadies Madrid. Si hay que documentar algún proceso concreto creamos un ticket separado. He puesto también el tweet https://twitter.com/python_es/status/1348716168002101248
