### ISSUE TITLE
Identificar todas las comunidades

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#64]
Identificar/listar todas las comunidades existentes, identificar contacto principal y proponer/preparar una mesa redonda con las portavoces. Estudiar periodicidad con todas las miembros, idealmente una vez cada 6 meses. Puede ser perfectamente un apartado en Discourse
Actualizar el mapa y la sección en la web.

**Comment by dukebody** [comment]
He echo una primera pasada basada en la lista de la web y he apuntado lo siguiente. Intentaré contactar con alguna comunidad local que conozca poco personalmente para ir haciendo fichas con la actividad que tienen y demás. :)

Python Madrid
https://www.python-madrid.es/
@python_madrid

Python Vigo
https://www.python-vigo.es/
@python_vigo

Python Málaga
https://www.meetup.com/es-ES/python_malaga/
@python_malaga

Python Valencia
https://www.meetup.com/es-ES/Python-Valencia-Meetup/
@python_vlc

Python Barcelona
https://pybcn.org/
@PyBCN

PyLadies Barcelona
https://www.meetup.com/PyLadies-BCN/
@PyLadiesBCN

Python Mallorca
https://www.meetup.com/es-ES/Mallorca-Python-Meetup/
@mallorca_python

Python Sevilla
https://www.meetup.com/es-ES/Python-Sevilla/
@python_sevilla

Python Zaragoza
https://plus.google.com/communities/103281359456269063508
@PythonZaragoza

Python Granada
https://www.python-granada.es/
@python_granada

Python Canarias
https://pythoncanarias.es/
@pythoncanarias

Python Alicante
https://www.meetup.com/python_alc/
@python_alc

Python San Sebastián
https://pyss.org/
@acpyss

Python Girona
https://pythongirona.cat/
@PythonGirona

PyData Madrid
https://www.meetup.com/PyData-Madrid/
@PyDataMad

Python Mallorca
https://www.meetup.com/Mallorca-Python-Meetup/
@pymallorca

PyData Mallorca
https://www.meetup.com/PyData-Mallorca/
@PyDataMallorca

Python Almería
https://twitter.com/HackLabAl  ?
https://www.meetup.com/Python-Almeria/

PyLadies Madrid
https://www.meetup.com/es-ES/PyLadiesMadrid/
@PyLadiesMadrid

ExtrePython
https://github.com/ExtrePython
@ExtrePython

**Comment by dukebody** [comment]
De cara a identificar los contactos principales y preparar esta mesa redonda, había pensado en abrir un hilo en el Discourse y mandar mensajes directos por Twitter, a los que tienen, pidiéndoles que escriban allí presentándose y tal. ¿Qué os parece?

**Comment by XaviTorello** [comment]
Perfecto @dukebody 🍻 

No perdamos de vista tener ni que sea un xls privado con los contactos de cada comunidad. Ya le encontraremos el lugar definitivo :b

**Comment by dukebody** [comment]
Hemos creado un documento con las distintas comunidades y sus contactos principales. Hemos hecho reuniones con muchas de ellas y tenemos previstas reuniones con las que quedan y van naciendo. Además ya tenemos grupos de Telegram y categoría de Discourse.

Doy este tiquet por cerrado. :D
