### ISSUE TITLE
Visibilizar las tareas en GH

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#71]
Para favorecer que más personas puedan participar / involucrarse.

**Comment by yamila-moreno** [comment]
He creado el proyecto aquí en GH; con 1 milestone por grupo grande de la candidatura.
Casi todas las iniciativas están ya volcadas.
Tenemos que ver si nos funciona bien como mecanismo de trabajo / visibilización .

**Comment by dukebody** [comment]
Promocionemos esto bien en la próxima asamblea de octubre de 2020.

**Comment by dukebody** [comment]
Ya está promocionado en la asamblea y acabo de enviar un tweet: https://twitter.com/python_es/status/1320337683558899713  Podemos seguir promocionando con tweets cada X tiempo, pero creo que la tarea principal ya está. :)
