### ISSUE TITLE
Abrir Discourse

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#72]
Abrir más el Discourse para que desde fuera se vean las discusiones (sin necesidad de ser socio/miembro)

**Comment by humitos** [comment]
Entiendo que esto ya está hecho y se puede cerrar. Sin estar "logeado" puedo leer los grupos públicos.

**Comment by dukebody** [comment]
Quedan algunos grupos internos que tenemos que decidir qué hacemos, ya que tienen conversaciones de cuando el grupo estaba cerrado. Creo que lo que haré será mover estas conversaciones a un archivo y crear grupos nuevos abiertos, así no habrá problemas.

**Comment by dukebody** [comment]
Hecho con el grupo de la PyConES. Considero esta tarea finiquitada. Por defecto discusiones públicas, al no ser que haya un motivo para que no lo sean. :)
