### ISSUE TITLE
Unificar infraestructura

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#74]
asociación, pycones, discourse, etc

**Comment by dukebody** [comment]
¿Cuál era el alcance de este ticket?

- Los servidores de la asociación en Scaleway ya están asociados a la tarjeta y CIF de la asociación, si no me equivoco.
- Las webs de las pycones las pasaremos a estático según se comenta en otro ticket.
- El discourse tb lo tenemos controlado.

¿Algo más?

**Comment by yamila-moreno** [comment]
El alcance dependía en parte de la primera reunión del GT Infra que no tuvo lugar aún :-/

**Comment by dukebody** [comment]
Ya están casi todas las webs de pycones pasadas a estático, ¿no? Faltaría la de 2018.

Luego también podemos pasar la propia web de la asociación a GH pages quizás, para no tener un servidor bloqueado con eso cuando el resto de cosas las tenemos en GH pages.

¿Qué opinas @yamila-moreno ? Fijémosle unos límites a esta tarea para que no quede abierta para siempre :D

**Comment by yamila-moreno** [comment]
- las webs de pycones están ya todas, salvo una, en gh-pages gestionados por la asociación
- hay un discourse en la infra de la asociación
- y otros servicios (pycones pasadas, pydays) en un servidor de la infra
- hay un mailman que usa algún grupo local y que no está gestionado directamente por el GT-infra pero sí por gente de la asociación

**Comment by yamila-moreno** [comment]
el objetivo de esta issue está de sobra cumplido y las pequeñas cosas pendientes tienen su propia issue. Cerrando pues!
