### ISSUE TITLE
Facilitar el pago de los meetups locales

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#8]
Facilitar el pago a los meetups locales de forma que los organizadores puedan solicitar el abono de los gastos al usar meetup.com a traves de un formulario o correo en la web de la asociacion.

**Comment by Juanlu001** [comment]
Relacionada: #16 (¿duplicada?)

**Comment by mariocj89** [comment]
He creado dos issues ya que los teníamos como dos puntos en la propuesta.

Los meetups parece algo más sencillo y concreto que está ya hablado
mientras que la otra issue es más abierta

**Comment by Juanlu001** [comment]
Para ir calentando, he mandado sendos mensajes a @marcosgabarda y @mabeldelgadob para los meetups de Python Valencia y PyLadies Madrid.

**Comment by mabeldelgadob** [comment]
Tras hablarlo con el resto de organizadoras de PyLadies Madrid (@mariamedp y @alipeji), hemos decicido seguir haciéndolo como hasta ahora, porque queremos que siga apareciendo una mujer al frente del grupo en meetup. 

Por otro lado, una vez que el traspaso de poderes de la tesorería sea plenamente funcional, si que podríamos abordar el tema de la creación del formulario de solicitud.

**Comment by dukebody** [comment]
Esto debería gestionarse ahora a través de la red pro de Meetup de la PSF. La PSF pagaría la cuenta de meetup de todos los meetups en su red. La cuenta de mail de Presidencia tiene los contactos de la gente que hay que contactar para añadir meetups a la red pro.

**Comment by dukebody** [comment]
@atugores , @XaviTorello tratemos de poner esto en la lista de "formas en las que Python España puede ayudar a tu comunidad local". Además de:
- Reservar espacios en nombre de la asociación.
- Seguro de responsabilidad civil, cuando esté listo.
- Etc.

**Comment by Juanlu001** [comment]
![Screenshot_2020-02-23 Tu cuenta Meetup(1)](https://user-images.githubusercontent.com/316517/75118185-37c5de00-5678-11ea-91d0-39ca62402af0.png)

¿Deberíamos mantener esto a la vez que la PSF tiene la red Pro? Lo digo para que alguien lo mire antes del 6 de abril

**Comment by dukebody** [comment]
Según he visto no todos los Meetups en los que Python España consta como organizador están dentro de la Red Pro de la PSF. 

Por ejemplo:
- Python Alicante. https://www.meetup.com/es-ES/python_alc/ No parece que esté en la red PSF.
- Python Madrid https://www.meetup.com/es-ES/python-madrid/ sí está 
- Python Valencia https://www.meetup.com/es-ES/Python-Valencia-Meetup/ No parece estar
- PyLadies Madrid https://www.meetup.com/es-ES/PyLadiesMadrid/ Sí
- Python Almería https://www.meetup.com/es-ES/Python-Almeria/ No

Los puntos rojos son los que están en la red pro de la PSF:
![image](https://user-images.githubusercontent.com/41953/75118729-e5d38700-567c-11ea-8f2c-929b09940183.png)
(Canarias tampoco está).

Creo que aún queda curro por hacer antes de poder cancelar la subscripción de plan de organizador.

**Comment by dukebody** [comment]
He creado https://github.com/python-spain/asociacion/issues/43 para hacer track del tema Red Pro de la PSF.

**Comment by dukebody** [comment]
Esto forma parte del documento de ayuda a comunidades locales del que se está encargando @atugores

**Comment by dukebody** [comment]
Cierro esta issue porque ya estamos tratando el tema de pago de las cuotas de Meetup.com en #43.
