### ISSUE TITLE
Portal de empleo en Discourse

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#80]

**Comment by dukebody** [comment]
El otro día escribí al Telegram de socios y publiqué algún tweet, pero de momento no hay ninguna oferta nueva. La semana que viene intentaré contactar por Twitter o lo que sea con algunas empresas que patrocinaron PyConES otros años ofreciéndoles el espacio, a ver si se anima la cosa. :)

**Comment by dukebody** [comment]
Al final no contacté con las empresas por Twitter. Pero creo que tampoco hay que volverse loco. Les decimos a las comunidades que tenemos esta vía para publicar ofertas de trabajo y se la pueden ofrecer a las empresas que les contacten, además de sus propias listas internas. Y a los patrocinadores de eventos propios de Python España tipo PyConES y tal, les ofrecemos también este espacio.

**Comment by bameda** [comment]
Ya existe una primera versión funcionando en https://comunidad.es.python.org/c/empleo Hay unas normas iniciales de publicacion aqui https://comunidad.es.python.org/t/como-publicar-una-oferta/20 y las ofertas que llegan se mueven por twitter también.
