### ISSUE TITLE
Traducir tutorial oficial de Python.org

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#81]
Podría ir a un GT.
El objetivo es traducir el tutorial y que se aloje en la documentación oficial de python.org.

**Comment by dukebody** [comment]
Parece que esto ya se está moviendo con @raulcd , @humitos y otra gente de la comunidad PyAr. Ver https://pyar.discourse.group/t/documentacion-oficial-de-python-en-espanol/238. Vamosss :D

**Comment by humitos** [comment]
Ya existe la version del tutorial oficial de Python en Español en https://tutorial.python.org.ar/en/latest/ --está en la versión 3.6.3. Sin embargo, es algo que se hizo hace bastantes años utilizando una estructura diferente a la oficial (Python no tenía forma de extender su documentación).


Sería bueno unir los esfuerzos y utilizar la estructura nueva para que sea la documentación de Python oficial en Español.

**Comment by humitos** [comment]
Estamos trabajando acá https://github.com/PyCampES/python-docs-es. Se migró lo que había en PyAr y se hizo merge con lo que había en el repositorio de Raúl.

**Comment by humitos** [comment]
Supongo que este issue se puede cerrar. El grupo de traductores está bastante consolidado ya (~60 en Telegram, ~25 activas). La traducción **ya es parte de la documentación oficial de Python** (https://docs.python.org/es/3.8/) y todo va viento en popa.

Tenemos una guía para colaborar en https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html y hasta la traducción de código de conducta oficial de la PSF en https://python-docs-es.readthedocs.io/page/coc.html

**Comment by dukebody** [comment]
Perfecto, ¡gracias por el curro!
