### ISSUE TITLE
PySurf con otras comunidades no pythónicas

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#87]
Pysurf con otras comunidades no necesariamente de Python. Que la gente se pueda proponer para dar charlas en otras comunidades.

**Comment by astrojuanlu** [comment]
¿Relacionado o duplicado de #54?

**Comment by yamila-moreno** [comment]
Está relacionado, pero creo que no duplicado. Al menos nacieron de dos propuestas distintas.

Esta es más para comunidades no pythónicas, y los contenidos pueden ser distintos, así como los inputs (no es lo mismo mirar comunidades de python cerca de mi pronvicia) que comunidades tecnológicas o no cerca de mi casa.

**Comment by astrojuanlu** [comment]
Ah, perdón, leí "pysurf" en diagonal y la parte de "no pythónicas" ni la vi :pray:

**Comment by dukebody** [comment]
La gente de Vigo nos ha comentado que gracias a VigoTech están haciendo este tipo de cosas. Y en Sevilla https://svqtech.com/ también ayuda a esto. Probablemente podemos intentar promocionar que se creen y desarrollen este tipo de "agrupaciones locales de comunidades tecnológicas", siguiendo el ejemplo de estas dos.

cc/ @anarey @Peibolvig

**Comment by Peibolvig** [comment]
Por si aporta algo aquí tenéis el link a la web de VigoTech (está en gallego, pero creo que se capta la idea ;)
https://vigotech.org

**Comment by dukebody** [comment]
Hemos creado una red de comunidades tecnológicas a nivel español y estamos planeando hacer los primeros eventos centrados en promoción de la diversidad. :)

**Comment by dukebody** [comment]
Esto está: https://www.youtube.com/watch?v=et5k0eGQmGs&t=1s
