### ISSUE TITLE
Reescribir estatutos con lenguaje inclusivo

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/asociacion#89]

**Comment by dukebody** [comment]
También está en https://github.com/python-spain/asociacion/issues/89

**Comment by yamila-moreno** [comment]
El PR tiene ya una primera revisión a fondo con los cambios. Por ahora, hemos adoptado una versión muy reduccionista de "diversidad", dado que solo hacemos una duplicidad de género; considero que es un primer paso y que estaría bien revisarlo tal y como está, pero que merecerá otras revisiones.

**Está como para recibir feedback de primer nivel**. Después arreglo los commits y pasamos a buscar el siguiente nivel de feedback.

**Comment by dukebody** [comment]
¡¡¡¡Conseguido!!!!
