### ISSUE TITLE
Crear un punto de encuentro para todas las organizaciones locales

### ISSUE THREAD

**Issue by mariocj89** [python-spain/asociacion#9]
A menudo organizaciones locales y regionales tienen dudas y preguntas que pueden ya haber sido aboradadas por otros grupos. Esta tarea consiste en crear una plataforma en la que diferentes grupos puedan compartir experiencias y ayuda a otros a formarse.

**Comment by maigimenez** [comment]
En el [acta](https://github.com/python-spain/actas/blob/master/acta-2018-04-08.rst) del 4 de Abril se comenzó a abordar este asunto, pero debido a su complejidad se relegó a una siguiente reunión monográfica.

**Comment by XaviTorello** [comment]
Hemos preparado un draft en https://trello.com/b/w4ENWLc0/grupos-locales, si os interesa avisadnos y os damos acceso (tiradnos un privi por gitter o tlgram con vuestro usuario de Trello).

La idea es ir madurando el concepto y poder analizar conjuntamente si puede ser interesante disponer de un grupo / comité dónde se representen todos los grupos locales.

**Comment by dukebody** [comment]
Tenemos el grupo de Telegram y https://comunidad.es.python.org/c/comunidades-locales/20.
