### ISSUE TITLE
Mover informes DMARC a una lista de distribución separada

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#92]
Ahora mismo el registro DNS DMARC apunta a it@es.python.org. Como potencialmente se pueden recibir muchos mails (¿uno diario?) en esta dirección, probablemente convenga dirigir los informes a otra lista tipo dmarc-reports@es.python.org.

La lista ya la he creado, falta permitir que reciba mensajes desde el exterior (aún no tengo permisos) y cambiar el registro DNS.

**Comment by XaviTorello** [comment]
Grants añadidos, y registros en NS para es.python.org y es.pycon.org apuntados a dmarc-reports@es.pycon.org

Dejo la issue abierta a la espera de confirmar que entran correctamente una vez se propague.

**Comment by dukebody** [comment]
Ey, tiene q ser a dmarc-reports@es.python.org, no es.pycon.org. ¿Errata aquí o allí?

**Comment by XaviTorello** [comment]
Ambas resuelven sobre el mismo grupo, así centralizamos los informes en un único lugar

**Comment by XaviTorello** [comment]
Cerramos issue dando la tarea por completada, se ha recibido el primer informe dmarc en el nuevo grupo.

Gracias a todos
