### ISSUE TITLE
Crear monitores de webs varias de Python España

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#93]
Nos ha pasado más de una vez que, por diversas razones, se nos han caído servicios como las webs de las PyConES, y no nos hemos dado cuenta hasta pasado un tiempo.

Deberíamos tener un servicio tipo Pingdom que comprobase que nuestras webs princpales no están caídas. 

https://geekflare.com/monitor-website-uptime/

**Comment by dukebody** [comment]
He hecho una prueba con el servicio Freshpings, que permite monitorear hasta 50 sitios de forma gratuita, y ya ha detectado 3 caídos :(

![image](https://user-images.githubusercontent.com/41953/83400458-2a508a80-a403-11ea-9709-6530ca98ed0d.png)

**Comment by yamila-moreno** [comment]
Gracias!
