### ISSUE TITLE
Mover webs de PyConES de servidores APSL a Scaleway

### ISSUE THREAD

**Issue by dukebody** [python-spain/asociacion#94]
Si no me equivoco creo que las webs de las PyConES de 2019 y 2020 están en los servidores de APSL. Dentro de la estrategia de mover todos los servicios de la asociación a servidores controlados por la asociación, deberíamos mover esto también.

**Comment by XaviTorello** [comment]
Quizá seria mejor paralizar esta tarea y estudiar si es mejor pasarlas a estático y servirlas via `gh-pages` o similares.

Qué pensáis @eduherraiz @yamila-moreno @dukebody?

**Comment by yamila-moreno** [comment]
Buenas!
Si lo entiendo bien diría que requieren dos soluciones distintas:

**Pycones 2019**. Ya terminó y ya no require de más cambios. Estoy de acuerdo en pasarla a estática y publicarla.
En principio en scaleway tenemos alguna web estática; no tengo una opinión fuerte sobre gh-pages o detrás de un proyx nuestro, pero sí creo que deberíamos usar el mismo sistema. Así que podemos llevar esta cuestión al GT de infra y adoptar la misma medida para el resto de servicios estáticos.

**Pycones 2020** Entiendo que hablamos de Pycones 2021 porque la de 2020 no se va a realizar y creo que la web (en contexto 2020) no va a tener más recorrido, ¿es así? Si hablamos la web de la próxima pycones, creo que por ahora debería mantenerse el sistema que preifera quien lo vaya a gestionar; hay un django usado y reusado con éxito en el pasado y si sigue sirviendo, sería maravilloso desde el punto de vista DRY. Sobre esto, @aaloy estábamos pendientes de poner la web en la infra de scaleway; en esta máquina solo van estáticos y dockers: pongamos que la web de pycones 2021 se expone internamente en el puerto 5006.

**Comment by yamila-moreno** [comment]
Pues al final sí hubo pycones2020 :D Está siendo ya mismo y esto no se movió. Así que añado la web de 2020 para pasarla a estático y desplegarla desde gh-pages también. Cierro esta issue porque se va a mover desde las correspondientes migraciones.

¡Gracias!

**Comment by dukebody** [comment]
@yamila-moreno 2020 está en estático desde GH pages: https://github.com/python-spain/PyConES2020-web :D

**Comment by yamila-moreno** [comment]
Perdón, no di todo el contexto. Sé que está en estático, pero aun así:
- moverlo a su correspondiente PyConES-2020-static daría homogeneidad lo que es bueno (el resto van a estar así)
- (y la oportunidad de más participación para ese evento del que usted me habla)

Será una migración más sencilla, pero aun así creo que es bueno hacerla :)
