### ISSUE TITLE
Migración cuentas PyConES

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#96]
Existen 3 buzones relacionados con el dominio es.pycon.org:
- [X] contact@2019.es.pycon.org
- [X] sponsor@2020.es.pycon.org
- [X] contact@2020.es.pycon.org

Mientras el GT de la PyConES 2020/2021 define cómo quiere gestionar el mail (Grupo con varios aliases vs mb tradicionales) propongo migrar las mb a las cuentas de snapshot:
-  _contact@2019.es.pycon.org
- _sponsor@2020.es.pycon.org
- _contact@2020.es.pycon.org

**Comment by dukebody** [comment]
¿Quizá en lugar de migrar a buzones se pueden migrar a grupos de Google? A lo mejor en el grupo se puede tomar una decisión rápida y así no hace falta repetir curro. Probablemente lo más sencillo sería mover todo 2020 a un grupo único, y 2019 a otro grupo.

**Comment by XaviTorello** [comment]
Ya está todo migrado a las cuentas de snapshot y JCea ya ha podido dar de baja el sistema de mail antiguo.

Sobre la decisión relativa a cómo lo quiere gestionar el GT PyConES, depende totalmente de ellos. Les comenté que lo estudiaran hace unos días.

Es mejor que una decisión no bloqueé la migración, por eso tiré millas creando los snapshot (igual que hicimos con las cuentas de la junta).

Crear un grupo, y volcar los mails desde las cuentas de snapshot será relativamente sencillo. Renombrar los snapshots a "cuentas normales" también.

Dejemos que ellos puedan estudiarlo y adaptémoslo a sus necesidades. Si?

**Comment by XaviTorello** [comment]
Validado en la reunión de JD de hoy. Cerramos issue.

Cuando el GT-PyConES tenga claro hacia donde ir abrimos nueva issue.

Gracias @all!
