### ISSUE TITLE
Activar interacción por mail con discourse

### ISSUE THREAD

**Issue by XaviTorello** [python-spain/asociacion#98]
La idea es poder contestar una notificación de un thread para añadir una respuesta directamente en Discourse.

Si vemos que es muy complejo lo paramos, a priori es configurar pop3 en Discourse y activar esta funcionalidad.

**Comment by dukebody** [comment]
https://meta.discourse.org/t/set-up-reply-via-email-support/14003

**Comment by pablo-grande** [comment]
:hand: on it

**Comment by pablo-grande** [comment]
Hola @dukebody , estoy mirando esto ahora y en enlace que has pasado el paso número 5 creo que no puedo hacerlo, quizá hay que ser administrador del Discourse o tener permisos o algo.
Por ahora he creado una cuenta de Gmail (python.es.discourse.replies@gmail.com) y le he activado el POP3.

**Comment by sincorchetes** [comment]
Ya se ha contactado con ASPL para su configuración, la pelota queda en su tejado.

**Comment by pablo-grande** [comment]
Entonces puedo borrar esa dirección de correo? ([python.es.discourse.replies@gmail.com](mailto:python.es.discourse.replies@gmail.com))

**Comment by sincorchetes** [comment]
Se ha vuelto contactar con ASPL y están con las gestiones, le he pasado las credenciales para el correo que ellos sugirieron: replies-discourse@comunidad.es.python.org

@pablo-grande , se puede eliminar sin problemas.

**Comment by sincorchetes** [comment]
Verificado, ya se puede responder via email.
